/* tslint:disable */
/* eslint-disable */
/**
 * Hey Bible App API
 * Public API for accessing Bible app data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiImagesGet200ResponseOneOf1ImagesInner } from './ApiImagesGet200ResponseOneOf1ImagesInner';
import {
    ApiImagesGet200ResponseOneOf1ImagesInnerFromJSON,
    ApiImagesGet200ResponseOneOf1ImagesInnerFromJSONTyped,
    ApiImagesGet200ResponseOneOf1ImagesInnerToJSON,
    ApiImagesGet200ResponseOneOf1ImagesInnerToJSONTyped,
} from './ApiImagesGet200ResponseOneOf1ImagesInner';

/**
 * Multiple images response (when ID is not specified)
 * @export
 * @interface ApiImagesGet200ResponseOneOf1
 */
export interface ApiImagesGet200ResponseOneOf1 {
    /**
     * Array of images (no signed URLs for performance)
     * @type {Array<ApiImagesGet200ResponseOneOf1ImagesInner>}
     * @memberof ApiImagesGet200ResponseOneOf1
     */
    images?: Array<ApiImagesGet200ResponseOneOf1ImagesInner>;
    /**
     * Number of images returned
     * @type {number}
     * @memberof ApiImagesGet200ResponseOneOf1
     */
    count?: number;
    /**
     * Current offset
     * @type {number}
     * @memberof ApiImagesGet200ResponseOneOf1
     */
    offset?: number;
    /**
     * Current limit
     * @type {number}
     * @memberof ApiImagesGet200ResponseOneOf1
     */
    limit?: number;
}

/**
 * Check if a given object implements the ApiImagesGet200ResponseOneOf1 interface.
 */
export function instanceOfApiImagesGet200ResponseOneOf1(value: object): value is ApiImagesGet200ResponseOneOf1 {
    return true;
}

export function ApiImagesGet200ResponseOneOf1FromJSON(json: any): ApiImagesGet200ResponseOneOf1 {
    return ApiImagesGet200ResponseOneOf1FromJSONTyped(json, false);
}

export function ApiImagesGet200ResponseOneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiImagesGet200ResponseOneOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'images': json['images'] == null ? undefined : ((json['images'] as Array<any>).map(ApiImagesGet200ResponseOneOf1ImagesInnerFromJSON)),
        'count': json['count'] == null ? undefined : json['count'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'limit': json['limit'] == null ? undefined : json['limit'],
    };
}

export function ApiImagesGet200ResponseOneOf1ToJSON(json: any): ApiImagesGet200ResponseOneOf1 {
    return ApiImagesGet200ResponseOneOf1ToJSONTyped(json, false);
}

export function ApiImagesGet200ResponseOneOf1ToJSONTyped(value?: ApiImagesGet200ResponseOneOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'images': value['images'] == null ? undefined : ((value['images'] as Array<any>).map(ApiImagesGet200ResponseOneOf1ImagesInnerToJSON)),
        'count': value['count'],
        'offset': value['offset'],
        'limit': value['limit'],
    };
}

