/* tslint:disable */
/* eslint-disable */
/**
 * Hey Bible App API
 * Public API for accessing Bible app data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiImagesGet200ResponseOneOfImage } from './ApiImagesGet200ResponseOneOfImage';
import {
    ApiImagesGet200ResponseOneOfImageFromJSON,
    ApiImagesGet200ResponseOneOfImageFromJSONTyped,
    ApiImagesGet200ResponseOneOfImageToJSON,
    ApiImagesGet200ResponseOneOfImageToJSONTyped,
} from './ApiImagesGet200ResponseOneOfImage';

/**
 * Single image response (when ID is specified)
 * @export
 * @interface ApiImagesGet200ResponseOneOf
 */
export interface ApiImagesGet200ResponseOneOf {
    /**
     * 
     * @type {ApiImagesGet200ResponseOneOfImage}
     * @memberof ApiImagesGet200ResponseOneOf
     */
    image?: ApiImagesGet200ResponseOneOfImage;
}

/**
 * Check if a given object implements the ApiImagesGet200ResponseOneOf interface.
 */
export function instanceOfApiImagesGet200ResponseOneOf(value: object): value is ApiImagesGet200ResponseOneOf {
    return true;
}

export function ApiImagesGet200ResponseOneOfFromJSON(json: any): ApiImagesGet200ResponseOneOf {
    return ApiImagesGet200ResponseOneOfFromJSONTyped(json, false);
}

export function ApiImagesGet200ResponseOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiImagesGet200ResponseOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'image': json['image'] == null ? undefined : ApiImagesGet200ResponseOneOfImageFromJSON(json['image']),
    };
}

export function ApiImagesGet200ResponseOneOfToJSON(json: any): ApiImagesGet200ResponseOneOf {
    return ApiImagesGet200ResponseOneOfToJSONTyped(json, false);
}

export function ApiImagesGet200ResponseOneOfToJSONTyped(value?: ApiImagesGet200ResponseOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'image': ApiImagesGet200ResponseOneOfImageToJSON(value['image']),
    };
}

