/* tslint:disable */
/* eslint-disable */
/**
 * Hey Bible App API
 * Public API for accessing Bible app data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ApiImagesGet200ResponseOneOf } from './ApiImagesGet200ResponseOneOf';
import {
    instanceOfApiImagesGet200ResponseOneOf,
    ApiImagesGet200ResponseOneOfFromJSON,
    ApiImagesGet200ResponseOneOfFromJSONTyped,
    ApiImagesGet200ResponseOneOfToJSON,
} from './ApiImagesGet200ResponseOneOf';
import type { ApiImagesGet200ResponseOneOf1 } from './ApiImagesGet200ResponseOneOf1';
import {
    instanceOfApiImagesGet200ResponseOneOf1,
    ApiImagesGet200ResponseOneOf1FromJSON,
    ApiImagesGet200ResponseOneOf1FromJSONTyped,
    ApiImagesGet200ResponseOneOf1ToJSON,
} from './ApiImagesGet200ResponseOneOf1';

/**
 * @type ApiImagesGet200Response
 * 
 * @export
 */
export type ApiImagesGet200Response = ApiImagesGet200ResponseOneOf | ApiImagesGet200ResponseOneOf1;

export function ApiImagesGet200ResponseFromJSON(json: any): ApiImagesGet200Response {
    return ApiImagesGet200ResponseFromJSONTyped(json, false);
}

export function ApiImagesGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiImagesGet200Response {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfApiImagesGet200ResponseOneOf(json)) {
        return ApiImagesGet200ResponseOneOfFromJSONTyped(json, true);
    }
    if (instanceOfApiImagesGet200ResponseOneOf1(json)) {
        return ApiImagesGet200ResponseOneOf1FromJSONTyped(json, true);
    }

    return {} as any;
}

export function ApiImagesGet200ResponseToJSON(json: any): any {
    return ApiImagesGet200ResponseToJSONTyped(json, false);
}

export function ApiImagesGet200ResponseToJSONTyped(value?: ApiImagesGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfApiImagesGet200ResponseOneOf(value)) {
        return ApiImagesGet200ResponseOneOfToJSON(value as ApiImagesGet200ResponseOneOf);
    }
    if (instanceOfApiImagesGet200ResponseOneOf1(value)) {
        return ApiImagesGet200ResponseOneOf1ToJSON(value as ApiImagesGet200ResponseOneOf1);
    }

    return {};
}

