/* tslint:disable */
/* eslint-disable */
/**
 * Hey Bible App API
 * Public API for accessing Bible app data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiImagesGet200ResponseOneOfImage
 */
export interface ApiImagesGet200ResponseOneOfImage {
    /**
     * 
     * @type {number}
     * @memberof ApiImagesGet200ResponseOneOfImage
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiImagesGet200ResponseOneOfImage
     */
    verseId?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiImagesGet200ResponseOneOfImage
     */
    storagePath?: string;
    /**
     * Pre-signed URL to access the image (24 hour expiry)
     * @type {string}
     * @memberof ApiImagesGet200ResponseOneOfImage
     */
    signedUrl?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ApiImagesGet200ResponseOneOfImage
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof ApiImagesGet200ResponseOneOfImage
     */
    prompt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiImagesGet200ResponseOneOfImage
     */
    size?: string | null;
    /**
     * Associated verse information
     * @type {object}
     * @memberof ApiImagesGet200ResponseOneOfImage
     */
    verses?: object;
}

/**
 * Check if a given object implements the ApiImagesGet200ResponseOneOfImage interface.
 */
export function instanceOfApiImagesGet200ResponseOneOfImage(value: object): value is ApiImagesGet200ResponseOneOfImage {
    return true;
}

export function ApiImagesGet200ResponseOneOfImageFromJSON(json: any): ApiImagesGet200ResponseOneOfImage {
    return ApiImagesGet200ResponseOneOfImageFromJSONTyped(json, false);
}

export function ApiImagesGet200ResponseOneOfImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiImagesGet200ResponseOneOfImage {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'verseId': json['verse_id'] == null ? undefined : json['verse_id'],
        'storagePath': json['storage_path'] == null ? undefined : json['storage_path'],
        'signedUrl': json['signed_url'] == null ? undefined : json['signed_url'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'prompt': json['prompt'] == null ? undefined : json['prompt'],
        'size': json['size'] == null ? undefined : json['size'],
        'verses': json['verses'] == null ? undefined : json['verses'],
    };
}

export function ApiImagesGet200ResponseOneOfImageToJSON(json: any): ApiImagesGet200ResponseOneOfImage {
    return ApiImagesGet200ResponseOneOfImageToJSONTyped(json, false);
}

export function ApiImagesGet200ResponseOneOfImageToJSONTyped(value?: ApiImagesGet200ResponseOneOfImage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'verse_id': value['verseId'],
        'storage_path': value['storagePath'],
        'signed_url': value['signedUrl'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'prompt': value['prompt'],
        'size': value['size'],
        'verses': value['verses'],
    };
}

