/* tslint:disable */
/* eslint-disable */
/**
 * Hey Bible App API
 * Public API for accessing Bible app data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiImagesGet200ResponseOneOf1ImagesInner
 */
export interface ApiImagesGet200ResponseOneOf1ImagesInner {
    /**
     * 
     * @type {number}
     * @memberof ApiImagesGet200ResponseOneOf1ImagesInner
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiImagesGet200ResponseOneOf1ImagesInner
     */
    verseId?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiImagesGet200ResponseOneOf1ImagesInner
     */
    storagePath?: string;
    /**
     * 
     * @type {Date}
     * @memberof ApiImagesGet200ResponseOneOf1ImagesInner
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof ApiImagesGet200ResponseOneOf1ImagesInner
     */
    prompt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiImagesGet200ResponseOneOf1ImagesInner
     */
    size?: string | null;
    /**
     * Associated verse information
     * @type {object}
     * @memberof ApiImagesGet200ResponseOneOf1ImagesInner
     */
    verses?: object;
}

/**
 * Check if a given object implements the ApiImagesGet200ResponseOneOf1ImagesInner interface.
 */
export function instanceOfApiImagesGet200ResponseOneOf1ImagesInner(value: object): value is ApiImagesGet200ResponseOneOf1ImagesInner {
    return true;
}

export function ApiImagesGet200ResponseOneOf1ImagesInnerFromJSON(json: any): ApiImagesGet200ResponseOneOf1ImagesInner {
    return ApiImagesGet200ResponseOneOf1ImagesInnerFromJSONTyped(json, false);
}

export function ApiImagesGet200ResponseOneOf1ImagesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiImagesGet200ResponseOneOf1ImagesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'verseId': json['verse_id'] == null ? undefined : json['verse_id'],
        'storagePath': json['storage_path'] == null ? undefined : json['storage_path'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'prompt': json['prompt'] == null ? undefined : json['prompt'],
        'size': json['size'] == null ? undefined : json['size'],
        'verses': json['verses'] == null ? undefined : json['verses'],
    };
}

export function ApiImagesGet200ResponseOneOf1ImagesInnerToJSON(json: any): ApiImagesGet200ResponseOneOf1ImagesInner {
    return ApiImagesGet200ResponseOneOf1ImagesInnerToJSONTyped(json, false);
}

export function ApiImagesGet200ResponseOneOf1ImagesInnerToJSONTyped(value?: ApiImagesGet200ResponseOneOf1ImagesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'verse_id': value['verseId'],
        'storage_path': value['storagePath'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'prompt': value['prompt'],
        'size': value['size'],
        'verses': value['verses'],
    };
}

