/* tslint:disable */
/* eslint-disable */
/**
 * Hey Bible App API
 * Public API for accessing Bible app data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiNotesGet200ResponseOneOf1NotesInner
 */
export interface ApiNotesGet200ResponseOneOf1NotesInner {
    /**
     * 
     * @type {number}
     * @memberof ApiNotesGet200ResponseOneOf1NotesInner
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiNotesGet200ResponseOneOf1NotesInner
     */
    verseId?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiNotesGet200ResponseOneOf1NotesInner
     */
    content?: string;
    /**
     * 
     * @type {Date}
     * @memberof ApiNotesGet200ResponseOneOf1NotesInner
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ApiNotesGet200ResponseOneOf1NotesInner
     */
    lastModified?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ApiNotesGet200ResponseOneOf1NotesInner
     */
    userId?: string;
    /**
     * Associated verse information
     * @type {object}
     * @memberof ApiNotesGet200ResponseOneOf1NotesInner
     */
    verses?: object;
}

/**
 * Check if a given object implements the ApiNotesGet200ResponseOneOf1NotesInner interface.
 */
export function instanceOfApiNotesGet200ResponseOneOf1NotesInner(value: object): value is ApiNotesGet200ResponseOneOf1NotesInner {
    return true;
}

export function ApiNotesGet200ResponseOneOf1NotesInnerFromJSON(json: any): ApiNotesGet200ResponseOneOf1NotesInner {
    return ApiNotesGet200ResponseOneOf1NotesInnerFromJSONTyped(json, false);
}

export function ApiNotesGet200ResponseOneOf1NotesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiNotesGet200ResponseOneOf1NotesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'verseId': json['verse_id'] == null ? undefined : json['verse_id'],
        'content': json['content'] == null ? undefined : json['content'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'lastModified': json['last_modified'] == null ? undefined : (new Date(json['last_modified'])),
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'verses': json['verses'] == null ? undefined : json['verses'],
    };
}

export function ApiNotesGet200ResponseOneOf1NotesInnerToJSON(json: any): ApiNotesGet200ResponseOneOf1NotesInner {
    return ApiNotesGet200ResponseOneOf1NotesInnerToJSONTyped(json, false);
}

export function ApiNotesGet200ResponseOneOf1NotesInnerToJSONTyped(value?: ApiNotesGet200ResponseOneOf1NotesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'verse_id': value['verseId'],
        'content': value['content'],
        'created_at': value['createdAt'] === null ? null : ((value['createdAt'] as any)?.toISOString()),
        'last_modified': value['lastModified'] === null ? null : ((value['lastModified'] as any)?.toISOString()),
        'user_id': value['userId'],
        'verses': value['verses'],
    };
}

