/* tslint:disable */
/* eslint-disable */
/**
 * Hey Bible App API
 * Public API for accessing Bible app data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiNotesGet200ResponseOneOfNote } from './ApiNotesGet200ResponseOneOfNote';
import {
    ApiNotesGet200ResponseOneOfNoteFromJSON,
    ApiNotesGet200ResponseOneOfNoteFromJSONTyped,
    ApiNotesGet200ResponseOneOfNoteToJSON,
    ApiNotesGet200ResponseOneOfNoteToJSONTyped,
} from './ApiNotesGet200ResponseOneOfNote';

/**
 * Single note response (when ID is specified)
 * @export
 * @interface ApiNotesGet200ResponseOneOf
 */
export interface ApiNotesGet200ResponseOneOf {
    /**
     * 
     * @type {ApiNotesGet200ResponseOneOfNote}
     * @memberof ApiNotesGet200ResponseOneOf
     */
    note?: ApiNotesGet200ResponseOneOfNote;
}

/**
 * Check if a given object implements the ApiNotesGet200ResponseOneOf interface.
 */
export function instanceOfApiNotesGet200ResponseOneOf(value: object): value is ApiNotesGet200ResponseOneOf {
    return true;
}

export function ApiNotesGet200ResponseOneOfFromJSON(json: any): ApiNotesGet200ResponseOneOf {
    return ApiNotesGet200ResponseOneOfFromJSONTyped(json, false);
}

export function ApiNotesGet200ResponseOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiNotesGet200ResponseOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'note': json['note'] == null ? undefined : ApiNotesGet200ResponseOneOfNoteFromJSON(json['note']),
    };
}

export function ApiNotesGet200ResponseOneOfToJSON(json: any): ApiNotesGet200ResponseOneOf {
    return ApiNotesGet200ResponseOneOfToJSONTyped(json, false);
}

export function ApiNotesGet200ResponseOneOfToJSONTyped(value?: ApiNotesGet200ResponseOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'note': ApiNotesGet200ResponseOneOfNoteToJSON(value['note']),
    };
}

