/* tslint:disable */
/* eslint-disable */
/**
 * Hey Bible App API
 * Public API for accessing Bible app data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiNotesGet200ResponseOneOfNoteVerses } from './ApiNotesGet200ResponseOneOfNoteVerses';
import {
    ApiNotesGet200ResponseOneOfNoteVersesFromJSON,
    ApiNotesGet200ResponseOneOfNoteVersesFromJSONTyped,
    ApiNotesGet200ResponseOneOfNoteVersesToJSON,
    ApiNotesGet200ResponseOneOfNoteVersesToJSONTyped,
} from './ApiNotesGet200ResponseOneOfNoteVerses';

/**
 * 
 * @export
 * @interface ApiNotesGet200ResponseOneOfNote
 */
export interface ApiNotesGet200ResponseOneOfNote {
    /**
     * 
     * @type {number}
     * @memberof ApiNotesGet200ResponseOneOfNote
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiNotesGet200ResponseOneOfNote
     */
    verseId?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiNotesGet200ResponseOneOfNote
     */
    content?: string;
    /**
     * 
     * @type {Date}
     * @memberof ApiNotesGet200ResponseOneOfNote
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ApiNotesGet200ResponseOneOfNote
     */
    lastModified?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ApiNotesGet200ResponseOneOfNote
     */
    userId?: string;
    /**
     * 
     * @type {ApiNotesGet200ResponseOneOfNoteVerses}
     * @memberof ApiNotesGet200ResponseOneOfNote
     */
    verses?: ApiNotesGet200ResponseOneOfNoteVerses;
}

/**
 * Check if a given object implements the ApiNotesGet200ResponseOneOfNote interface.
 */
export function instanceOfApiNotesGet200ResponseOneOfNote(value: object): value is ApiNotesGet200ResponseOneOfNote {
    return true;
}

export function ApiNotesGet200ResponseOneOfNoteFromJSON(json: any): ApiNotesGet200ResponseOneOfNote {
    return ApiNotesGet200ResponseOneOfNoteFromJSONTyped(json, false);
}

export function ApiNotesGet200ResponseOneOfNoteFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiNotesGet200ResponseOneOfNote {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'verseId': json['verse_id'] == null ? undefined : json['verse_id'],
        'content': json['content'] == null ? undefined : json['content'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'lastModified': json['last_modified'] == null ? undefined : (new Date(json['last_modified'])),
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'verses': json['verses'] == null ? undefined : ApiNotesGet200ResponseOneOfNoteVersesFromJSON(json['verses']),
    };
}

export function ApiNotesGet200ResponseOneOfNoteToJSON(json: any): ApiNotesGet200ResponseOneOfNote {
    return ApiNotesGet200ResponseOneOfNoteToJSONTyped(json, false);
}

export function ApiNotesGet200ResponseOneOfNoteToJSONTyped(value?: ApiNotesGet200ResponseOneOfNote | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'verse_id': value['verseId'],
        'content': value['content'],
        'created_at': value['createdAt'] === null ? null : ((value['createdAt'] as any)?.toISOString()),
        'last_modified': value['lastModified'] === null ? null : ((value['lastModified'] as any)?.toISOString()),
        'user_id': value['userId'],
        'verses': ApiNotesGet200ResponseOneOfNoteVersesToJSON(value['verses']),
    };
}

