/* tslint:disable */
/* eslint-disable */
/**
 * Hey Bible App API
 * Public API for accessing Bible app data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ApiNotesGet200ResponseOneOf } from './ApiNotesGet200ResponseOneOf';
import {
    instanceOfApiNotesGet200ResponseOneOf,
    ApiNotesGet200ResponseOneOfFromJSON,
    ApiNotesGet200ResponseOneOfFromJSONTyped,
    ApiNotesGet200ResponseOneOfToJSON,
} from './ApiNotesGet200ResponseOneOf';
import type { ApiNotesGet200ResponseOneOf1 } from './ApiNotesGet200ResponseOneOf1';
import {
    instanceOfApiNotesGet200ResponseOneOf1,
    ApiNotesGet200ResponseOneOf1FromJSON,
    ApiNotesGet200ResponseOneOf1FromJSONTyped,
    ApiNotesGet200ResponseOneOf1ToJSON,
} from './ApiNotesGet200ResponseOneOf1';

/**
 * @type ApiNotesGet200Response
 * 
 * @export
 */
export type ApiNotesGet200Response = ApiNotesGet200ResponseOneOf | ApiNotesGet200ResponseOneOf1;

export function ApiNotesGet200ResponseFromJSON(json: any): ApiNotesGet200Response {
    return ApiNotesGet200ResponseFromJSONTyped(json, false);
}

export function ApiNotesGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiNotesGet200Response {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfApiNotesGet200ResponseOneOf(json)) {
        return ApiNotesGet200ResponseOneOfFromJSONTyped(json, true);
    }
    if (instanceOfApiNotesGet200ResponseOneOf1(json)) {
        return ApiNotesGet200ResponseOneOf1FromJSONTyped(json, true);
    }

    return {} as any;
}

export function ApiNotesGet200ResponseToJSON(json: any): any {
    return ApiNotesGet200ResponseToJSONTyped(json, false);
}

export function ApiNotesGet200ResponseToJSONTyped(value?: ApiNotesGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfApiNotesGet200ResponseOneOf(value)) {
        return ApiNotesGet200ResponseOneOfToJSON(value as ApiNotesGet200ResponseOneOf);
    }
    if (instanceOfApiNotesGet200ResponseOneOf1(value)) {
        return ApiNotesGet200ResponseOneOf1ToJSON(value as ApiNotesGet200ResponseOneOf1);
    }

    return {};
}

