/* tslint:disable */
/* eslint-disable */
/**
 * Hey Bible App API
 * Public API for accessing Bible app data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiVersesGet200ResponseOneOfVerse } from './ApiVersesGet200ResponseOneOfVerse';
import {
    ApiVersesGet200ResponseOneOfVerseFromJSON,
    ApiVersesGet200ResponseOneOfVerseFromJSONTyped,
    ApiVersesGet200ResponseOneOfVerseToJSON,
    ApiVersesGet200ResponseOneOfVerseToJSONTyped,
} from './ApiVersesGet200ResponseOneOfVerse';

/**
 * Single verse response (when ID is specified)
 * @export
 * @interface ApiVersesGet200ResponseOneOf
 */
export interface ApiVersesGet200ResponseOneOf {
    /**
     * 
     * @type {ApiVersesGet200ResponseOneOfVerse}
     * @memberof ApiVersesGet200ResponseOneOf
     */
    verse?: ApiVersesGet200ResponseOneOfVerse;
}

/**
 * Check if a given object implements the ApiVersesGet200ResponseOneOf interface.
 */
export function instanceOfApiVersesGet200ResponseOneOf(value: object): value is ApiVersesGet200ResponseOneOf {
    return true;
}

export function ApiVersesGet200ResponseOneOfFromJSON(json: any): ApiVersesGet200ResponseOneOf {
    return ApiVersesGet200ResponseOneOfFromJSONTyped(json, false);
}

export function ApiVersesGet200ResponseOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiVersesGet200ResponseOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'verse': json['verse'] == null ? undefined : ApiVersesGet200ResponseOneOfVerseFromJSON(json['verse']),
    };
}

export function ApiVersesGet200ResponseOneOfToJSON(json: any): ApiVersesGet200ResponseOneOf {
    return ApiVersesGet200ResponseOneOfToJSONTyped(json, false);
}

export function ApiVersesGet200ResponseOneOfToJSONTyped(value?: ApiVersesGet200ResponseOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'verse': ApiVersesGet200ResponseOneOfVerseToJSON(value['verse']),
    };
}

