/* tslint:disable */
/* eslint-disable */
/**
 * Hey Bible App API
 * Public API for accessing Bible app data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiVersesGet200ResponseOneOf1VersesInner } from './ApiVersesGet200ResponseOneOf1VersesInner';
import {
    ApiVersesGet200ResponseOneOf1VersesInnerFromJSON,
    ApiVersesGet200ResponseOneOf1VersesInnerFromJSONTyped,
    ApiVersesGet200ResponseOneOf1VersesInnerToJSON,
    ApiVersesGet200ResponseOneOf1VersesInnerToJSONTyped,
} from './ApiVersesGet200ResponseOneOf1VersesInner';

/**
 * Multiple verses response (when ID is not specified)
 * @export
 * @interface ApiVersesGet200ResponseOneOf1
 */
export interface ApiVersesGet200ResponseOneOf1 {
    /**
     * 
     * @type {Array<ApiVersesGet200ResponseOneOf1VersesInner>}
     * @memberof ApiVersesGet200ResponseOneOf1
     */
    verses?: Array<ApiVersesGet200ResponseOneOf1VersesInner>;
    /**
     * Number of verses returned
     * @type {number}
     * @memberof ApiVersesGet200ResponseOneOf1
     */
    count?: number;
    /**
     * Current offset
     * @type {number}
     * @memberof ApiVersesGet200ResponseOneOf1
     */
    offset?: number;
    /**
     * Current limit
     * @type {number}
     * @memberof ApiVersesGet200ResponseOneOf1
     */
    limit?: number;
}

/**
 * Check if a given object implements the ApiVersesGet200ResponseOneOf1 interface.
 */
export function instanceOfApiVersesGet200ResponseOneOf1(value: object): value is ApiVersesGet200ResponseOneOf1 {
    return true;
}

export function ApiVersesGet200ResponseOneOf1FromJSON(json: any): ApiVersesGet200ResponseOneOf1 {
    return ApiVersesGet200ResponseOneOf1FromJSONTyped(json, false);
}

export function ApiVersesGet200ResponseOneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiVersesGet200ResponseOneOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'verses': json['verses'] == null ? undefined : ((json['verses'] as Array<any>).map(ApiVersesGet200ResponseOneOf1VersesInnerFromJSON)),
        'count': json['count'] == null ? undefined : json['count'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'limit': json['limit'] == null ? undefined : json['limit'],
    };
}

export function ApiVersesGet200ResponseOneOf1ToJSON(json: any): ApiVersesGet200ResponseOneOf1 {
    return ApiVersesGet200ResponseOneOf1ToJSONTyped(json, false);
}

export function ApiVersesGet200ResponseOneOf1ToJSONTyped(value?: ApiVersesGet200ResponseOneOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'verses': value['verses'] == null ? undefined : ((value['verses'] as Array<any>).map(ApiVersesGet200ResponseOneOf1VersesInnerToJSON)),
        'count': value['count'],
        'offset': value['offset'],
        'limit': value['limit'],
    };
}

