/* tslint:disable */
/* eslint-disable */
/**
 * Hey Bible App API
 * Public API for accessing Bible app data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiVersesGet200ResponseOneOf1VersesInner
 */
export interface ApiVersesGet200ResponseOneOf1VersesInner {
    /**
     * 
     * @type {number}
     * @memberof ApiVersesGet200ResponseOneOf1VersesInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiVersesGet200ResponseOneOf1VersesInner
     */
    bibleId?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiVersesGet200ResponseOneOf1VersesInner
     */
    book?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiVersesGet200ResponseOneOf1VersesInner
     */
    chapter?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiVersesGet200ResponseOneOf1VersesInner
     */
    startVerse?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiVersesGet200ResponseOneOf1VersesInner
     */
    endVerse?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiVersesGet200ResponseOneOf1VersesInner
     */
    content?: string;
    /**
     * 
     * @type {Date}
     * @memberof ApiVersesGet200ResponseOneOf1VersesInner
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ApiVersesGet200ResponseOneOf1VersesInner
     */
    lastUpdated?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof ApiVersesGet200ResponseOneOf1VersesInner
     */
    isFavorite?: boolean;
}

/**
 * Check if a given object implements the ApiVersesGet200ResponseOneOf1VersesInner interface.
 */
export function instanceOfApiVersesGet200ResponseOneOf1VersesInner(value: object): value is ApiVersesGet200ResponseOneOf1VersesInner {
    return true;
}

export function ApiVersesGet200ResponseOneOf1VersesInnerFromJSON(json: any): ApiVersesGet200ResponseOneOf1VersesInner {
    return ApiVersesGet200ResponseOneOf1VersesInnerFromJSONTyped(json, false);
}

export function ApiVersesGet200ResponseOneOf1VersesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiVersesGet200ResponseOneOf1VersesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'bibleId': json['bible_id'] == null ? undefined : json['bible_id'],
        'book': json['book'] == null ? undefined : json['book'],
        'chapter': json['chapter'] == null ? undefined : json['chapter'],
        'startVerse': json['start_verse'] == null ? undefined : json['start_verse'],
        'endVerse': json['end_verse'] == null ? undefined : json['end_verse'],
        'content': json['content'] == null ? undefined : json['content'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'lastUpdated': json['last_updated'] == null ? undefined : (new Date(json['last_updated'])),
        'isFavorite': json['is_favorite'] == null ? undefined : json['is_favorite'],
    };
}

export function ApiVersesGet200ResponseOneOf1VersesInnerToJSON(json: any): ApiVersesGet200ResponseOneOf1VersesInner {
    return ApiVersesGet200ResponseOneOf1VersesInnerToJSONTyped(json, false);
}

export function ApiVersesGet200ResponseOneOf1VersesInnerToJSONTyped(value?: ApiVersesGet200ResponseOneOf1VersesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'bible_id': value['bibleId'],
        'book': value['book'],
        'chapter': value['chapter'],
        'start_verse': value['startVerse'],
        'end_verse': value['endVerse'],
        'content': value['content'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'last_updated': value['lastUpdated'] === null ? null : ((value['lastUpdated'] as any)?.toISOString()),
        'is_favorite': value['isFavorite'],
    };
}

