/* tslint:disable */
/* eslint-disable */
/**
 * Hey Bible App API
 * Public API for accessing Bible app data
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BiblesGet200ResponseBiblesInner
 */
export interface BiblesGet200ResponseBiblesInner {
    /**
     * Unique Bible identifier
     * @type {string}
     * @memberof BiblesGet200ResponseBiblesInner
     */
    id?: string;
    /**
     * Full name (e.g. "English Standard Version")
     * @type {string}
     * @memberof BiblesGet200ResponseBiblesInner
     */
    name?: string;
    /**
     * Short code (e.g. "esv")
     * @type {string}
     * @memberof BiblesGet200ResponseBiblesInner
     */
    abbreviation?: string;
    /**
     * 
     * @type {string}
     * @memberof BiblesGet200ResponseBiblesInner
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof BiblesGet200ResponseBiblesInner
     */
    source?: BiblesGet200ResponseBiblesInnerSourceEnum;
}


/**
 * @export
 */
export const BiblesGet200ResponseBiblesInnerSourceEnum = {
    Private: 'private',
    ApiBible: 'api.bible'
} as const;
export type BiblesGet200ResponseBiblesInnerSourceEnum = typeof BiblesGet200ResponseBiblesInnerSourceEnum[keyof typeof BiblesGet200ResponseBiblesInnerSourceEnum];


/**
 * Check if a given object implements the BiblesGet200ResponseBiblesInner interface.
 */
export function instanceOfBiblesGet200ResponseBiblesInner(value: object): value is BiblesGet200ResponseBiblesInner {
    return true;
}

export function BiblesGet200ResponseBiblesInnerFromJSON(json: any): BiblesGet200ResponseBiblesInner {
    return BiblesGet200ResponseBiblesInnerFromJSONTyped(json, false);
}

export function BiblesGet200ResponseBiblesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): BiblesGet200ResponseBiblesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'abbreviation': json['abbreviation'] == null ? undefined : json['abbreviation'],
        'description': json['description'] == null ? undefined : json['description'],
        'source': json['source'] == null ? undefined : json['source'],
    };
}

export function BiblesGet200ResponseBiblesInnerToJSON(json: any): BiblesGet200ResponseBiblesInner {
    return BiblesGet200ResponseBiblesInnerToJSONTyped(json, false);
}

export function BiblesGet200ResponseBiblesInnerToJSONTyped(value?: BiblesGet200ResponseBiblesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'abbreviation': value['abbreviation'],
        'description': value['description'],
        'source': value['source'],
    };
}

