/* tslint:disable */
/* eslint-disable */
/**
 * Hey Bible App API
 * Public API for accessing Bible app data
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BiblesGet200ResponseBiblesInner } from './BiblesGet200ResponseBiblesInner';
import {
    BiblesGet200ResponseBiblesInnerFromJSON,
    BiblesGet200ResponseBiblesInnerFromJSONTyped,
    BiblesGet200ResponseBiblesInnerToJSON,
    BiblesGet200ResponseBiblesInnerToJSONTyped,
} from './BiblesGet200ResponseBiblesInner';

/**
 * 
 * @export
 * @interface BiblesGet200Response
 */
export interface BiblesGet200Response {
    /**
     * 
     * @type {Array<BiblesGet200ResponseBiblesInner>}
     * @memberof BiblesGet200Response
     */
    bibles?: Array<BiblesGet200ResponseBiblesInner>;
}

/**
 * Check if a given object implements the BiblesGet200Response interface.
 */
export function instanceOfBiblesGet200Response(value: object): value is BiblesGet200Response {
    return true;
}

export function BiblesGet200ResponseFromJSON(json: any): BiblesGet200Response {
    return BiblesGet200ResponseFromJSONTyped(json, false);
}

export function BiblesGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BiblesGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'bibles': json['bibles'] == null ? undefined : ((json['bibles'] as Array<any>).map(BiblesGet200ResponseBiblesInnerFromJSON)),
    };
}

export function BiblesGet200ResponseToJSON(json: any): BiblesGet200Response {
    return BiblesGet200ResponseToJSONTyped(json, false);
}

export function BiblesGet200ResponseToJSONTyped(value?: BiblesGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bibles': value['bibles'] == null ? undefined : ((value['bibles'] as Array<any>).map(BiblesGet200ResponseBiblesInnerToJSON)),
    };
}

