/* tslint:disable */
/* eslint-disable */
/**
 * Hey Bible App API
 * Public API for accessing Bible app data
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BooksGet200ResponseBooksInner
 */
export interface BooksGet200ResponseBooksInner {
    /**
     * Display name (e.g. "Genesis")
     * @type {string}
     * @memberof BooksGet200ResponseBooksInner
     */
    name?: string;
    /**
     * 3-letter code (e.g. "GEN")
     * @type {string}
     * @memberof BooksGet200ResponseBooksInner
     */
    code?: string;
    /**
     * Number of chapters in the book
     * @type {number}
     * @memberof BooksGet200ResponseBooksInner
     */
    chapters?: number;
}

/**
 * Check if a given object implements the BooksGet200ResponseBooksInner interface.
 */
export function instanceOfBooksGet200ResponseBooksInner(value: object): value is BooksGet200ResponseBooksInner {
    return true;
}

export function BooksGet200ResponseBooksInnerFromJSON(json: any): BooksGet200ResponseBooksInner {
    return BooksGet200ResponseBooksInnerFromJSONTyped(json, false);
}

export function BooksGet200ResponseBooksInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): BooksGet200ResponseBooksInner {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'code': json['code'] == null ? undefined : json['code'],
        'chapters': json['chapters'] == null ? undefined : json['chapters'],
    };
}

export function BooksGet200ResponseBooksInnerToJSON(json: any): BooksGet200ResponseBooksInner {
    return BooksGet200ResponseBooksInnerToJSONTyped(json, false);
}

export function BooksGet200ResponseBooksInnerToJSONTyped(value?: BooksGet200ResponseBooksInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'code': value['code'],
        'chapters': value['chapters'],
    };
}

