/* tslint:disable */
/* eslint-disable */
/**
 * Hey Bible App API
 * Public API for accessing Bible app data
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BooksGet200ResponseBooksInner } from './BooksGet200ResponseBooksInner';
import {
    BooksGet200ResponseBooksInnerFromJSON,
    BooksGet200ResponseBooksInnerFromJSONTyped,
    BooksGet200ResponseBooksInnerToJSON,
    BooksGet200ResponseBooksInnerToJSONTyped,
} from './BooksGet200ResponseBooksInner';

/**
 * 
 * @export
 * @interface BooksGet200Response
 */
export interface BooksGet200Response {
    /**
     * 
     * @type {Array<BooksGet200ResponseBooksInner>}
     * @memberof BooksGet200Response
     */
    books?: Array<BooksGet200ResponseBooksInner>;
}

/**
 * Check if a given object implements the BooksGet200Response interface.
 */
export function instanceOfBooksGet200Response(value: object): value is BooksGet200Response {
    return true;
}

export function BooksGet200ResponseFromJSON(json: any): BooksGet200Response {
    return BooksGet200ResponseFromJSONTyped(json, false);
}

export function BooksGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BooksGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'books': json['books'] == null ? undefined : ((json['books'] as Array<any>).map(BooksGet200ResponseBooksInnerFromJSON)),
    };
}

export function BooksGet200ResponseToJSON(json: any): BooksGet200Response {
    return BooksGet200ResponseToJSONTyped(json, false);
}

export function BooksGet200ResponseToJSONTyped(value?: BooksGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'books': value['books'] == null ? undefined : ((value['books'] as Array<any>).map(BooksGet200ResponseBooksInnerToJSON)),
    };
}

