/* tslint:disable */
/* eslint-disable */
/**
 * Hey Bible App API
 * Public API for accessing Bible app data
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatsGet200ResponseOneOf1ChatChatMessagesInner
 */
export interface ChatsGet200ResponseOneOf1ChatChatMessagesInner {
    /**
     * 
     * @type {string}
     * @memberof ChatsGet200ResponseOneOf1ChatChatMessagesInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatsGet200ResponseOneOf1ChatChatMessagesInner
     */
    role?: ChatsGet200ResponseOneOf1ChatChatMessagesInnerRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof ChatsGet200ResponseOneOf1ChatChatMessagesInner
     */
    content?: string;
    /**
     * 
     * @type {Date}
     * @memberof ChatsGet200ResponseOneOf1ChatChatMessagesInner
     */
    createdAt?: Date;
}


/**
 * @export
 */
export const ChatsGet200ResponseOneOf1ChatChatMessagesInnerRoleEnum = {
    User: 'user',
    Assistant: 'assistant'
} as const;
export type ChatsGet200ResponseOneOf1ChatChatMessagesInnerRoleEnum = typeof ChatsGet200ResponseOneOf1ChatChatMessagesInnerRoleEnum[keyof typeof ChatsGet200ResponseOneOf1ChatChatMessagesInnerRoleEnum];


/**
 * Check if a given object implements the ChatsGet200ResponseOneOf1ChatChatMessagesInner interface.
 */
export function instanceOfChatsGet200ResponseOneOf1ChatChatMessagesInner(value: object): value is ChatsGet200ResponseOneOf1ChatChatMessagesInner {
    return true;
}

export function ChatsGet200ResponseOneOf1ChatChatMessagesInnerFromJSON(json: any): ChatsGet200ResponseOneOf1ChatChatMessagesInner {
    return ChatsGet200ResponseOneOf1ChatChatMessagesInnerFromJSONTyped(json, false);
}

export function ChatsGet200ResponseOneOf1ChatChatMessagesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatsGet200ResponseOneOf1ChatChatMessagesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'role': json['role'] == null ? undefined : json['role'],
        'content': json['content'] == null ? undefined : json['content'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
    };
}

export function ChatsGet200ResponseOneOf1ChatChatMessagesInnerToJSON(json: any): ChatsGet200ResponseOneOf1ChatChatMessagesInner {
    return ChatsGet200ResponseOneOf1ChatChatMessagesInnerToJSONTyped(json, false);
}

export function ChatsGet200ResponseOneOf1ChatChatMessagesInnerToJSONTyped(value?: ChatsGet200ResponseOneOf1ChatChatMessagesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'role': value['role'],
        'content': value['content'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
    };
}

