/* tslint:disable */
/* eslint-disable */
/**
 * Hey Bible App API
 * Public API for accessing Bible app data
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ChatsGet200ResponseOneOf } from './ChatsGet200ResponseOneOf';
import {
    instanceOfChatsGet200ResponseOneOf,
    ChatsGet200ResponseOneOfFromJSON,
    ChatsGet200ResponseOneOfFromJSONTyped,
    ChatsGet200ResponseOneOfToJSON,
} from './ChatsGet200ResponseOneOf';
import type { ChatsGet200ResponseOneOf1 } from './ChatsGet200ResponseOneOf1';
import {
    instanceOfChatsGet200ResponseOneOf1,
    ChatsGet200ResponseOneOf1FromJSON,
    ChatsGet200ResponseOneOf1FromJSONTyped,
    ChatsGet200ResponseOneOf1ToJSON,
} from './ChatsGet200ResponseOneOf1';

/**
 * @type ChatsGet200Response
 * 
 * @export
 */
export type ChatsGet200Response = ChatsGet200ResponseOneOf | ChatsGet200ResponseOneOf1;

export function ChatsGet200ResponseFromJSON(json: any): ChatsGet200Response {
    return ChatsGet200ResponseFromJSONTyped(json, false);
}

export function ChatsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatsGet200Response {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfChatsGet200ResponseOneOf(json)) {
        return ChatsGet200ResponseOneOfFromJSONTyped(json, true);
    }
    if (instanceOfChatsGet200ResponseOneOf1(json)) {
        return ChatsGet200ResponseOneOf1FromJSONTyped(json, true);
    }

    return {} as any;
}

export function ChatsGet200ResponseToJSON(json: any): any {
    return ChatsGet200ResponseToJSONTyped(json, false);
}

export function ChatsGet200ResponseToJSONTyped(value?: ChatsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfChatsGet200ResponseOneOf(value)) {
        return ChatsGet200ResponseOneOfToJSON(value as ChatsGet200ResponseOneOf);
    }
    if (instanceOfChatsGet200ResponseOneOf1(value)) {
        return ChatsGet200ResponseOneOf1ToJSON(value as ChatsGet200ResponseOneOf1);
    }

    return {};
}

