/* tslint:disable */
/* eslint-disable */
/**
 * Hey Bible App API
 * Public API for accessing Bible app data
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatsGet200ResponseOneOfChatsInner } from './ChatsGet200ResponseOneOfChatsInner';
import {
    ChatsGet200ResponseOneOfChatsInnerFromJSON,
    ChatsGet200ResponseOneOfChatsInnerFromJSONTyped,
    ChatsGet200ResponseOneOfChatsInnerToJSON,
    ChatsGet200ResponseOneOfChatsInnerToJSONTyped,
} from './ChatsGet200ResponseOneOfChatsInner';

/**
 * List response (no ID specified)
 * @export
 * @interface ChatsGet200ResponseOneOf
 */
export interface ChatsGet200ResponseOneOf {
    /**
     * 
     * @type {Array<ChatsGet200ResponseOneOfChatsInner>}
     * @memberof ChatsGet200ResponseOneOf
     */
    chats?: Array<ChatsGet200ResponseOneOfChatsInner>;
}

/**
 * Check if a given object implements the ChatsGet200ResponseOneOf interface.
 */
export function instanceOfChatsGet200ResponseOneOf(value: object): value is ChatsGet200ResponseOneOf {
    return true;
}

export function ChatsGet200ResponseOneOfFromJSON(json: any): ChatsGet200ResponseOneOf {
    return ChatsGet200ResponseOneOfFromJSONTyped(json, false);
}

export function ChatsGet200ResponseOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatsGet200ResponseOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'chats': json['chats'] == null ? undefined : ((json['chats'] as Array<any>).map(ChatsGet200ResponseOneOfChatsInnerFromJSON)),
    };
}

export function ChatsGet200ResponseOneOfToJSON(json: any): ChatsGet200ResponseOneOf {
    return ChatsGet200ResponseOneOfToJSONTyped(json, false);
}

export function ChatsGet200ResponseOneOfToJSONTyped(value?: ChatsGet200ResponseOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chats': value['chats'] == null ? undefined : ((value['chats'] as Array<any>).map(ChatsGet200ResponseOneOfChatsInnerToJSON)),
    };
}

