/* tslint:disable */
/* eslint-disable */
/**
 * Hey Bible App API
 * Public API for accessing Bible app data
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatsGet200ResponseOneOfChatsInnerVerses } from './ChatsGet200ResponseOneOfChatsInnerVerses';
import {
    ChatsGet200ResponseOneOfChatsInnerVersesFromJSON,
    ChatsGet200ResponseOneOfChatsInnerVersesFromJSONTyped,
    ChatsGet200ResponseOneOfChatsInnerVersesToJSON,
    ChatsGet200ResponseOneOfChatsInnerVersesToJSONTyped,
} from './ChatsGet200ResponseOneOfChatsInnerVerses';
import type { ChatsGet200ResponseOneOf1ChatChatMessagesInner } from './ChatsGet200ResponseOneOf1ChatChatMessagesInner';
import {
    ChatsGet200ResponseOneOf1ChatChatMessagesInnerFromJSON,
    ChatsGet200ResponseOneOf1ChatChatMessagesInnerFromJSONTyped,
    ChatsGet200ResponseOneOf1ChatChatMessagesInnerToJSON,
    ChatsGet200ResponseOneOf1ChatChatMessagesInnerToJSONTyped,
} from './ChatsGet200ResponseOneOf1ChatChatMessagesInner';

/**
 * 
 * @export
 * @interface ChatsGet200ResponseOneOf1Chat
 */
export interface ChatsGet200ResponseOneOf1Chat {
    /**
     * 
     * @type {string}
     * @memberof ChatsGet200ResponseOneOf1Chat
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatsGet200ResponseOneOf1Chat
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChatsGet200ResponseOneOf1Chat
     */
    model?: string;
    /**
     * 
     * @type {Date}
     * @memberof ChatsGet200ResponseOneOf1Chat
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ChatsGet200ResponseOneOf1Chat
     */
    lastMessageAt?: Date;
    /**
     * 
     * @type {ChatsGet200ResponseOneOfChatsInnerVerses}
     * @memberof ChatsGet200ResponseOneOf1Chat
     */
    verses?: ChatsGet200ResponseOneOfChatsInnerVerses;
    /**
     * 
     * @type {Array<ChatsGet200ResponseOneOf1ChatChatMessagesInner>}
     * @memberof ChatsGet200ResponseOneOf1Chat
     */
    chatMessages?: Array<ChatsGet200ResponseOneOf1ChatChatMessagesInner>;
}

/**
 * Check if a given object implements the ChatsGet200ResponseOneOf1Chat interface.
 */
export function instanceOfChatsGet200ResponseOneOf1Chat(value: object): value is ChatsGet200ResponseOneOf1Chat {
    return true;
}

export function ChatsGet200ResponseOneOf1ChatFromJSON(json: any): ChatsGet200ResponseOneOf1Chat {
    return ChatsGet200ResponseOneOf1ChatFromJSONTyped(json, false);
}

export function ChatsGet200ResponseOneOf1ChatFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatsGet200ResponseOneOf1Chat {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'model': json['model'] == null ? undefined : json['model'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'lastMessageAt': json['last_message_at'] == null ? undefined : (new Date(json['last_message_at'])),
        'verses': json['verses'] == null ? undefined : ChatsGet200ResponseOneOfChatsInnerVersesFromJSON(json['verses']),
        'chatMessages': json['chat_messages'] == null ? undefined : ((json['chat_messages'] as Array<any>).map(ChatsGet200ResponseOneOf1ChatChatMessagesInnerFromJSON)),
    };
}

export function ChatsGet200ResponseOneOf1ChatToJSON(json: any): ChatsGet200ResponseOneOf1Chat {
    return ChatsGet200ResponseOneOf1ChatToJSONTyped(json, false);
}

export function ChatsGet200ResponseOneOf1ChatToJSONTyped(value?: ChatsGet200ResponseOneOf1Chat | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'model': value['model'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'last_message_at': value['lastMessageAt'] == null ? undefined : ((value['lastMessageAt']).toISOString()),
        'verses': ChatsGet200ResponseOneOfChatsInnerVersesToJSON(value['verses']),
        'chat_messages': value['chatMessages'] == null ? undefined : ((value['chatMessages'] as Array<any>).map(ChatsGet200ResponseOneOf1ChatChatMessagesInnerToJSON)),
    };
}

