/* tslint:disable */
/* eslint-disable */
/**
 * Hey Bible App API
 * Public API for accessing Bible app data
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatsGet200ResponseOneOf1Chat } from './ChatsGet200ResponseOneOf1Chat';
import {
    ChatsGet200ResponseOneOf1ChatFromJSON,
    ChatsGet200ResponseOneOf1ChatFromJSONTyped,
    ChatsGet200ResponseOneOf1ChatToJSON,
    ChatsGet200ResponseOneOf1ChatToJSONTyped,
} from './ChatsGet200ResponseOneOf1Chat';

/**
 * Detail response (ID specified)
 * @export
 * @interface ChatsGet200ResponseOneOf1
 */
export interface ChatsGet200ResponseOneOf1 {
    /**
     * 
     * @type {ChatsGet200ResponseOneOf1Chat}
     * @memberof ChatsGet200ResponseOneOf1
     */
    chat?: ChatsGet200ResponseOneOf1Chat;
}

/**
 * Check if a given object implements the ChatsGet200ResponseOneOf1 interface.
 */
export function instanceOfChatsGet200ResponseOneOf1(value: object): value is ChatsGet200ResponseOneOf1 {
    return true;
}

export function ChatsGet200ResponseOneOf1FromJSON(json: any): ChatsGet200ResponseOneOf1 {
    return ChatsGet200ResponseOneOf1FromJSONTyped(json, false);
}

export function ChatsGet200ResponseOneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatsGet200ResponseOneOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'chat': json['chat'] == null ? undefined : ChatsGet200ResponseOneOf1ChatFromJSON(json['chat']),
    };
}

export function ChatsGet200ResponseOneOf1ToJSON(json: any): ChatsGet200ResponseOneOf1 {
    return ChatsGet200ResponseOneOf1ToJSONTyped(json, false);
}

export function ChatsGet200ResponseOneOf1ToJSONTyped(value?: ChatsGet200ResponseOneOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chat': ChatsGet200ResponseOneOf1ChatToJSON(value['chat']),
    };
}

