/* tslint:disable */
/* eslint-disable */
/**
 * Hey Bible App API
 * Public API for accessing Bible app data
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FavoritesGet200ResponseFavoritesInnerTagsInner } from './FavoritesGet200ResponseFavoritesInnerTagsInner';
import {
    FavoritesGet200ResponseFavoritesInnerTagsInnerFromJSON,
    FavoritesGet200ResponseFavoritesInnerTagsInnerFromJSONTyped,
    FavoritesGet200ResponseFavoritesInnerTagsInnerToJSON,
    FavoritesGet200ResponseFavoritesInnerTagsInnerToJSONTyped,
} from './FavoritesGet200ResponseFavoritesInnerTagsInner';
import type { FavoritesGet200ResponseFavoritesInnerImagesInner } from './FavoritesGet200ResponseFavoritesInnerImagesInner';
import {
    FavoritesGet200ResponseFavoritesInnerImagesInnerFromJSON,
    FavoritesGet200ResponseFavoritesInnerImagesInnerFromJSONTyped,
    FavoritesGet200ResponseFavoritesInnerImagesInnerToJSON,
    FavoritesGet200ResponseFavoritesInnerImagesInnerToJSONTyped,
} from './FavoritesGet200ResponseFavoritesInnerImagesInner';
import type { FavoritesGet200ResponseFavoritesInnerNotesInner } from './FavoritesGet200ResponseFavoritesInnerNotesInner';
import {
    FavoritesGet200ResponseFavoritesInnerNotesInnerFromJSON,
    FavoritesGet200ResponseFavoritesInnerNotesInnerFromJSONTyped,
    FavoritesGet200ResponseFavoritesInnerNotesInnerToJSON,
    FavoritesGet200ResponseFavoritesInnerNotesInnerToJSONTyped,
} from './FavoritesGet200ResponseFavoritesInnerNotesInner';
import type { FavoritesGet200ResponseFavoritesInnerConversationsInner } from './FavoritesGet200ResponseFavoritesInnerConversationsInner';
import {
    FavoritesGet200ResponseFavoritesInnerConversationsInnerFromJSON,
    FavoritesGet200ResponseFavoritesInnerConversationsInnerFromJSONTyped,
    FavoritesGet200ResponseFavoritesInnerConversationsInnerToJSON,
    FavoritesGet200ResponseFavoritesInnerConversationsInnerToJSONTyped,
} from './FavoritesGet200ResponseFavoritesInnerConversationsInner';

/**
 * 
 * @export
 * @interface FavoritesGet200ResponseFavoritesInner
 */
export interface FavoritesGet200ResponseFavoritesInner {
    /**
     * 
     * @type {number}
     * @memberof FavoritesGet200ResponseFavoritesInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof FavoritesGet200ResponseFavoritesInner
     */
    userId?: string;
    /**
     * 
     * @type {Date}
     * @memberof FavoritesGet200ResponseFavoritesInner
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof FavoritesGet200ResponseFavoritesInner
     */
    book?: string;
    /**
     * 
     * @type {number}
     * @memberof FavoritesGet200ResponseFavoritesInner
     */
    chapter?: number;
    /**
     * 
     * @type {number}
     * @memberof FavoritesGet200ResponseFavoritesInner
     */
    startVerse?: number;
    /**
     * 
     * @type {number}
     * @memberof FavoritesGet200ResponseFavoritesInner
     */
    endVerse?: number;
    /**
     * 
     * @type {Date}
     * @memberof FavoritesGet200ResponseFavoritesInner
     */
    lastUpdated?: Date;
    /**
     * 
     * @type {string}
     * @memberof FavoritesGet200ResponseFavoritesInner
     */
    content?: string;
    /**
     * 
     * @type {string}
     * @memberof FavoritesGet200ResponseFavoritesInner
     */
    bibleId?: string;
    /**
     * 
     * @type {Array<FavoritesGet200ResponseFavoritesInnerNotesInner>}
     * @memberof FavoritesGet200ResponseFavoritesInner
     */
    notes?: Array<FavoritesGet200ResponseFavoritesInnerNotesInner>;
    /**
     * Image metadata (use /images?id= for signed URLs)
     * @type {Array<FavoritesGet200ResponseFavoritesInnerImagesInner>}
     * @memberof FavoritesGet200ResponseFavoritesInner
     */
    images?: Array<FavoritesGet200ResponseFavoritesInnerImagesInner>;
    /**
     * 
     * @type {Array<FavoritesGet200ResponseFavoritesInnerConversationsInner>}
     * @memberof FavoritesGet200ResponseFavoritesInner
     */
    conversations?: Array<FavoritesGet200ResponseFavoritesInnerConversationsInner>;
    /**
     * 
     * @type {Array<FavoritesGet200ResponseFavoritesInnerTagsInner>}
     * @memberof FavoritesGet200ResponseFavoritesInner
     */
    tags?: Array<FavoritesGet200ResponseFavoritesInnerTagsInner>;
}

/**
 * Check if a given object implements the FavoritesGet200ResponseFavoritesInner interface.
 */
export function instanceOfFavoritesGet200ResponseFavoritesInner(value: object): value is FavoritesGet200ResponseFavoritesInner {
    return true;
}

export function FavoritesGet200ResponseFavoritesInnerFromJSON(json: any): FavoritesGet200ResponseFavoritesInner {
    return FavoritesGet200ResponseFavoritesInnerFromJSONTyped(json, false);
}

export function FavoritesGet200ResponseFavoritesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): FavoritesGet200ResponseFavoritesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'book': json['book'] == null ? undefined : json['book'],
        'chapter': json['chapter'] == null ? undefined : json['chapter'],
        'startVerse': json['start_verse'] == null ? undefined : json['start_verse'],
        'endVerse': json['end_verse'] == null ? undefined : json['end_verse'],
        'lastUpdated': json['last_updated'] == null ? undefined : (new Date(json['last_updated'])),
        'content': json['content'] == null ? undefined : json['content'],
        'bibleId': json['bible_id'] == null ? undefined : json['bible_id'],
        'notes': json['notes'] == null ? undefined : ((json['notes'] as Array<any>).map(FavoritesGet200ResponseFavoritesInnerNotesInnerFromJSON)),
        'images': json['images'] == null ? undefined : ((json['images'] as Array<any>).map(FavoritesGet200ResponseFavoritesInnerImagesInnerFromJSON)),
        'conversations': json['conversations'] == null ? undefined : ((json['conversations'] as Array<any>).map(FavoritesGet200ResponseFavoritesInnerConversationsInnerFromJSON)),
        'tags': json['tags'] == null ? undefined : ((json['tags'] as Array<any>).map(FavoritesGet200ResponseFavoritesInnerTagsInnerFromJSON)),
    };
}

export function FavoritesGet200ResponseFavoritesInnerToJSON(json: any): FavoritesGet200ResponseFavoritesInner {
    return FavoritesGet200ResponseFavoritesInnerToJSONTyped(json, false);
}

export function FavoritesGet200ResponseFavoritesInnerToJSONTyped(value?: FavoritesGet200ResponseFavoritesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'user_id': value['userId'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'book': value['book'],
        'chapter': value['chapter'],
        'start_verse': value['startVerse'],
        'end_verse': value['endVerse'],
        'last_updated': value['lastUpdated'] == null ? undefined : ((value['lastUpdated']).toISOString()),
        'content': value['content'],
        'bible_id': value['bibleId'],
        'notes': value['notes'] == null ? undefined : ((value['notes'] as Array<any>).map(FavoritesGet200ResponseFavoritesInnerNotesInnerToJSON)),
        'images': value['images'] == null ? undefined : ((value['images'] as Array<any>).map(FavoritesGet200ResponseFavoritesInnerImagesInnerToJSON)),
        'conversations': value['conversations'] == null ? undefined : ((value['conversations'] as Array<any>).map(FavoritesGet200ResponseFavoritesInnerConversationsInnerToJSON)),
        'tags': value['tags'] == null ? undefined : ((value['tags'] as Array<any>).map(FavoritesGet200ResponseFavoritesInnerTagsInnerToJSON)),
    };
}

