/* tslint:disable */
/* eslint-disable */
/**
 * Hey Bible App API
 * Public API for accessing Bible app data
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FavoritesGet200ResponseFavoritesInnerNotesInner
 */
export interface FavoritesGet200ResponseFavoritesInnerNotesInner {
    /**
     * 
     * @type {number}
     * @memberof FavoritesGet200ResponseFavoritesInnerNotesInner
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof FavoritesGet200ResponseFavoritesInnerNotesInner
     */
    verseId?: number;
    /**
     * 
     * @type {string}
     * @memberof FavoritesGet200ResponseFavoritesInnerNotesInner
     */
    content?: string;
    /**
     * 
     * @type {Date}
     * @memberof FavoritesGet200ResponseFavoritesInnerNotesInner
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof FavoritesGet200ResponseFavoritesInnerNotesInner
     */
    lastModified?: Date | null;
}

/**
 * Check if a given object implements the FavoritesGet200ResponseFavoritesInnerNotesInner interface.
 */
export function instanceOfFavoritesGet200ResponseFavoritesInnerNotesInner(value: object): value is FavoritesGet200ResponseFavoritesInnerNotesInner {
    return true;
}

export function FavoritesGet200ResponseFavoritesInnerNotesInnerFromJSON(json: any): FavoritesGet200ResponseFavoritesInnerNotesInner {
    return FavoritesGet200ResponseFavoritesInnerNotesInnerFromJSONTyped(json, false);
}

export function FavoritesGet200ResponseFavoritesInnerNotesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): FavoritesGet200ResponseFavoritesInnerNotesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'verseId': json['verse_id'] == null ? undefined : json['verse_id'],
        'content': json['content'] == null ? undefined : json['content'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'lastModified': json['last_modified'] == null ? undefined : (new Date(json['last_modified'])),
    };
}

export function FavoritesGet200ResponseFavoritesInnerNotesInnerToJSON(json: any): FavoritesGet200ResponseFavoritesInnerNotesInner {
    return FavoritesGet200ResponseFavoritesInnerNotesInnerToJSONTyped(json, false);
}

export function FavoritesGet200ResponseFavoritesInnerNotesInnerToJSONTyped(value?: FavoritesGet200ResponseFavoritesInnerNotesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'verse_id': value['verseId'],
        'content': value['content'],
        'created_at': value['createdAt'] === null ? null : ((value['createdAt'] as any)?.toISOString()),
        'last_modified': value['lastModified'] === null ? null : ((value['lastModified'] as any)?.toISOString()),
    };
}

