/* tslint:disable */
/* eslint-disable */
/**
 * Hey Bible App API
 * Public API for accessing Bible app data
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FavoritesGet200ResponseFavoritesInnerTagsInner
 */
export interface FavoritesGet200ResponseFavoritesInnerTagsInner {
    /**
     * 
     * @type {number}
     * @memberof FavoritesGet200ResponseFavoritesInnerTagsInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof FavoritesGet200ResponseFavoritesInnerTagsInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof FavoritesGet200ResponseFavoritesInnerTagsInner
     */
    color?: string;
}

/**
 * Check if a given object implements the FavoritesGet200ResponseFavoritesInnerTagsInner interface.
 */
export function instanceOfFavoritesGet200ResponseFavoritesInnerTagsInner(value: object): value is FavoritesGet200ResponseFavoritesInnerTagsInner {
    return true;
}

export function FavoritesGet200ResponseFavoritesInnerTagsInnerFromJSON(json: any): FavoritesGet200ResponseFavoritesInnerTagsInner {
    return FavoritesGet200ResponseFavoritesInnerTagsInnerFromJSONTyped(json, false);
}

export function FavoritesGet200ResponseFavoritesInnerTagsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): FavoritesGet200ResponseFavoritesInnerTagsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'color': json['color'] == null ? undefined : json['color'],
    };
}

export function FavoritesGet200ResponseFavoritesInnerTagsInnerToJSON(json: any): FavoritesGet200ResponseFavoritesInnerTagsInner {
    return FavoritesGet200ResponseFavoritesInnerTagsInnerToJSONTyped(json, false);
}

export function FavoritesGet200ResponseFavoritesInnerTagsInnerToJSONTyped(value?: FavoritesGet200ResponseFavoritesInnerTagsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'color': value['color'],
    };
}

