/* tslint:disable */
/* eslint-disable */
/**
 * Hey Bible App API
 * Public API for accessing Bible app data
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FavoritesGet200ResponseFavoritesInner } from './FavoritesGet200ResponseFavoritesInner';
import {
    FavoritesGet200ResponseFavoritesInnerFromJSON,
    FavoritesGet200ResponseFavoritesInnerFromJSONTyped,
    FavoritesGet200ResponseFavoritesInnerToJSON,
    FavoritesGet200ResponseFavoritesInnerToJSONTyped,
} from './FavoritesGet200ResponseFavoritesInner';

/**
 * 
 * @export
 * @interface FavoritesGet200Response
 */
export interface FavoritesGet200Response {
    /**
     * 
     * @type {Array<FavoritesGet200ResponseFavoritesInner>}
     * @memberof FavoritesGet200Response
     */
    favorites?: Array<FavoritesGet200ResponseFavoritesInner>;
}

/**
 * Check if a given object implements the FavoritesGet200Response interface.
 */
export function instanceOfFavoritesGet200Response(value: object): value is FavoritesGet200Response {
    return true;
}

export function FavoritesGet200ResponseFromJSON(json: any): FavoritesGet200Response {
    return FavoritesGet200ResponseFromJSONTyped(json, false);
}

export function FavoritesGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FavoritesGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'favorites': json['favorites'] == null ? undefined : ((json['favorites'] as Array<any>).map(FavoritesGet200ResponseFavoritesInnerFromJSON)),
    };
}

export function FavoritesGet200ResponseToJSON(json: any): FavoritesGet200Response {
    return FavoritesGet200ResponseToJSONTyped(json, false);
}

export function FavoritesGet200ResponseToJSONTyped(value?: FavoritesGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'favorites': value['favorites'] == null ? undefined : ((value['favorites'] as Array<any>).map(FavoritesGet200ResponseFavoritesInnerToJSON)),
    };
}

