/* tslint:disable */
/* eslint-disable */
/**
 * Hey Bible App API
 * Public API for accessing Bible app data
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ImagesGet200ResponseOneOf } from './ImagesGet200ResponseOneOf';
import {
    instanceOfImagesGet200ResponseOneOf,
    ImagesGet200ResponseOneOfFromJSON,
    ImagesGet200ResponseOneOfFromJSONTyped,
    ImagesGet200ResponseOneOfToJSON,
} from './ImagesGet200ResponseOneOf';
import type { ImagesGet200ResponseOneOf1 } from './ImagesGet200ResponseOneOf1';
import {
    instanceOfImagesGet200ResponseOneOf1,
    ImagesGet200ResponseOneOf1FromJSON,
    ImagesGet200ResponseOneOf1FromJSONTyped,
    ImagesGet200ResponseOneOf1ToJSON,
} from './ImagesGet200ResponseOneOf1';

/**
 * @type ImagesGet200Response
 * 
 * @export
 */
export type ImagesGet200Response = ImagesGet200ResponseOneOf | ImagesGet200ResponseOneOf1;

export function ImagesGet200ResponseFromJSON(json: any): ImagesGet200Response {
    return ImagesGet200ResponseFromJSONTyped(json, false);
}

export function ImagesGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImagesGet200Response {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfImagesGet200ResponseOneOf(json)) {
        return ImagesGet200ResponseOneOfFromJSONTyped(json, true);
    }
    if (instanceOfImagesGet200ResponseOneOf1(json)) {
        return ImagesGet200ResponseOneOf1FromJSONTyped(json, true);
    }

    return {} as any;
}

export function ImagesGet200ResponseToJSON(json: any): any {
    return ImagesGet200ResponseToJSONTyped(json, false);
}

export function ImagesGet200ResponseToJSONTyped(value?: ImagesGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfImagesGet200ResponseOneOf(value)) {
        return ImagesGet200ResponseOneOfToJSON(value as ImagesGet200ResponseOneOf);
    }
    if (instanceOfImagesGet200ResponseOneOf1(value)) {
        return ImagesGet200ResponseOneOf1ToJSON(value as ImagesGet200ResponseOneOf1);
    }

    return {};
}

