/* tslint:disable */
/* eslint-disable */
/**
 * Hey Bible App API
 * Public API for accessing Bible app data
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImagesGet200ResponseOneOfImage } from './ImagesGet200ResponseOneOfImage';
import {
    ImagesGet200ResponseOneOfImageFromJSON,
    ImagesGet200ResponseOneOfImageFromJSONTyped,
    ImagesGet200ResponseOneOfImageToJSON,
    ImagesGet200ResponseOneOfImageToJSONTyped,
} from './ImagesGet200ResponseOneOfImage';

/**
 * Single image response (when ID is specified)
 * @export
 * @interface ImagesGet200ResponseOneOf
 */
export interface ImagesGet200ResponseOneOf {
    /**
     * 
     * @type {ImagesGet200ResponseOneOfImage}
     * @memberof ImagesGet200ResponseOneOf
     */
    image?: ImagesGet200ResponseOneOfImage;
}

/**
 * Check if a given object implements the ImagesGet200ResponseOneOf interface.
 */
export function instanceOfImagesGet200ResponseOneOf(value: object): value is ImagesGet200ResponseOneOf {
    return true;
}

export function ImagesGet200ResponseOneOfFromJSON(json: any): ImagesGet200ResponseOneOf {
    return ImagesGet200ResponseOneOfFromJSONTyped(json, false);
}

export function ImagesGet200ResponseOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImagesGet200ResponseOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'image': json['image'] == null ? undefined : ImagesGet200ResponseOneOfImageFromJSON(json['image']),
    };
}

export function ImagesGet200ResponseOneOfToJSON(json: any): ImagesGet200ResponseOneOf {
    return ImagesGet200ResponseOneOfToJSONTyped(json, false);
}

export function ImagesGet200ResponseOneOfToJSONTyped(value?: ImagesGet200ResponseOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'image': ImagesGet200ResponseOneOfImageToJSON(value['image']),
    };
}

