/* tslint:disable */
/* eslint-disable */
/**
 * Hey Bible App API
 * Public API for accessing Bible app data
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImagesGet200ResponseOneOfImages } from './ImagesGet200ResponseOneOfImages';
import {
    ImagesGet200ResponseOneOfImagesFromJSON,
    ImagesGet200ResponseOneOfImagesFromJSONTyped,
    ImagesGet200ResponseOneOfImagesToJSON,
    ImagesGet200ResponseOneOfImagesToJSONTyped,
} from './ImagesGet200ResponseOneOfImages';

/**
 * Single image response (when ID is specified)
 * @export
 * @interface ImagesGet200ResponseOneOf
 */
export interface ImagesGet200ResponseOneOf {
    /**
     * 
     * @type {ImagesGet200ResponseOneOfImages}
     * @memberof ImagesGet200ResponseOneOf
     */
    images?: ImagesGet200ResponseOneOfImages;
}

/**
 * Check if a given object implements the ImagesGet200ResponseOneOf interface.
 */
export function instanceOfImagesGet200ResponseOneOf(value: object): value is ImagesGet200ResponseOneOf {
    return true;
}

export function ImagesGet200ResponseOneOfFromJSON(json: any): ImagesGet200ResponseOneOf {
    return ImagesGet200ResponseOneOfFromJSONTyped(json, false);
}

export function ImagesGet200ResponseOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImagesGet200ResponseOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'images': json['images'] == null ? undefined : ImagesGet200ResponseOneOfImagesFromJSON(json['images']),
    };
}

export function ImagesGet200ResponseOneOfToJSON(json: any): ImagesGet200ResponseOneOf {
    return ImagesGet200ResponseOneOfToJSONTyped(json, false);
}

export function ImagesGet200ResponseOneOfToJSONTyped(value?: ImagesGet200ResponseOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'images': ImagesGet200ResponseOneOfImagesToJSON(value['images']),
    };
}

