/* tslint:disable */
/* eslint-disable */
/**
 * Hey Bible App API
 * Public API for accessing Bible app data
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { NotesGet200ResponseOneOf } from './NotesGet200ResponseOneOf';
import {
    instanceOfNotesGet200ResponseOneOf,
    NotesGet200ResponseOneOfFromJSON,
    NotesGet200ResponseOneOfFromJSONTyped,
    NotesGet200ResponseOneOfToJSON,
} from './NotesGet200ResponseOneOf';
import type { NotesGet200ResponseOneOf1 } from './NotesGet200ResponseOneOf1';
import {
    instanceOfNotesGet200ResponseOneOf1,
    NotesGet200ResponseOneOf1FromJSON,
    NotesGet200ResponseOneOf1FromJSONTyped,
    NotesGet200ResponseOneOf1ToJSON,
} from './NotesGet200ResponseOneOf1';

/**
 * @type NotesGet200Response
 * 
 * @export
 */
export type NotesGet200Response = NotesGet200ResponseOneOf | NotesGet200ResponseOneOf1;

export function NotesGet200ResponseFromJSON(json: any): NotesGet200Response {
    return NotesGet200ResponseFromJSONTyped(json, false);
}

export function NotesGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotesGet200Response {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfNotesGet200ResponseOneOf(json)) {
        return NotesGet200ResponseOneOfFromJSONTyped(json, true);
    }
    if (instanceOfNotesGet200ResponseOneOf1(json)) {
        return NotesGet200ResponseOneOf1FromJSONTyped(json, true);
    }

    return {} as any;
}

export function NotesGet200ResponseToJSON(json: any): any {
    return NotesGet200ResponseToJSONTyped(json, false);
}

export function NotesGet200ResponseToJSONTyped(value?: NotesGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfNotesGet200ResponseOneOf(value)) {
        return NotesGet200ResponseOneOfToJSON(value as NotesGet200ResponseOneOf);
    }
    if (instanceOfNotesGet200ResponseOneOf1(value)) {
        return NotesGet200ResponseOneOf1ToJSON(value as NotesGet200ResponseOneOf1);
    }

    return {};
}

