/* tslint:disable */
/* eslint-disable */
/**
 * Hey Bible App API
 * Public API for accessing Bible app data
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Associated verse information
 * @export
 * @interface NotesGet200ResponseOneOfNoteVerses
 */
export interface NotesGet200ResponseOneOfNoteVerses {
    /**
     * 
     * @type {number}
     * @memberof NotesGet200ResponseOneOfNoteVerses
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof NotesGet200ResponseOneOfNoteVerses
     */
    bibleId?: string;
    /**
     * 
     * @type {string}
     * @memberof NotesGet200ResponseOneOfNoteVerses
     */
    book?: string;
    /**
     * 
     * @type {number}
     * @memberof NotesGet200ResponseOneOfNoteVerses
     */
    chapter?: number;
    /**
     * 
     * @type {number}
     * @memberof NotesGet200ResponseOneOfNoteVerses
     */
    startVerse?: number;
    /**
     * 
     * @type {number}
     * @memberof NotesGet200ResponseOneOfNoteVerses
     */
    endVerse?: number;
    /**
     * 
     * @type {string}
     * @memberof NotesGet200ResponseOneOfNoteVerses
     */
    content?: string;
    /**
     * 
     * @type {Date}
     * @memberof NotesGet200ResponseOneOfNoteVerses
     */
    createdAt?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof NotesGet200ResponseOneOfNoteVerses
     */
    isFavorite?: boolean;
}

/**
 * Check if a given object implements the NotesGet200ResponseOneOfNoteVerses interface.
 */
export function instanceOfNotesGet200ResponseOneOfNoteVerses(value: object): value is NotesGet200ResponseOneOfNoteVerses {
    return true;
}

export function NotesGet200ResponseOneOfNoteVersesFromJSON(json: any): NotesGet200ResponseOneOfNoteVerses {
    return NotesGet200ResponseOneOfNoteVersesFromJSONTyped(json, false);
}

export function NotesGet200ResponseOneOfNoteVersesFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotesGet200ResponseOneOfNoteVerses {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'bibleId': json['bible_id'] == null ? undefined : json['bible_id'],
        'book': json['book'] == null ? undefined : json['book'],
        'chapter': json['chapter'] == null ? undefined : json['chapter'],
        'startVerse': json['start_verse'] == null ? undefined : json['start_verse'],
        'endVerse': json['end_verse'] == null ? undefined : json['end_verse'],
        'content': json['content'] == null ? undefined : json['content'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'isFavorite': json['is_favorite'] == null ? undefined : json['is_favorite'],
    };
}

export function NotesGet200ResponseOneOfNoteVersesToJSON(json: any): NotesGet200ResponseOneOfNoteVerses {
    return NotesGet200ResponseOneOfNoteVersesToJSONTyped(json, false);
}

export function NotesGet200ResponseOneOfNoteVersesToJSONTyped(value?: NotesGet200ResponseOneOfNoteVerses | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'bible_id': value['bibleId'],
        'book': value['book'],
        'chapter': value['chapter'],
        'start_verse': value['startVerse'],
        'end_verse': value['endVerse'],
        'content': value['content'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'is_favorite': value['isFavorite'],
    };
}

