/* tslint:disable */
/* eslint-disable */
/**
 * Hey Bible App API
 * Public API for accessing Bible app data
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotesGet200ResponseOneOfNotesVerses } from './NotesGet200ResponseOneOfNotesVerses';
import {
    NotesGet200ResponseOneOfNotesVersesFromJSON,
    NotesGet200ResponseOneOfNotesVersesFromJSONTyped,
    NotesGet200ResponseOneOfNotesVersesToJSON,
    NotesGet200ResponseOneOfNotesVersesToJSONTyped,
} from './NotesGet200ResponseOneOfNotesVerses';

/**
 * 
 * @export
 * @interface NotesGet200ResponseOneOfNotes
 */
export interface NotesGet200ResponseOneOfNotes {
    /**
     * 
     * @type {number}
     * @memberof NotesGet200ResponseOneOfNotes
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof NotesGet200ResponseOneOfNotes
     */
    verseId?: number;
    /**
     * 
     * @type {string}
     * @memberof NotesGet200ResponseOneOfNotes
     */
    content?: string;
    /**
     * 
     * @type {Date}
     * @memberof NotesGet200ResponseOneOfNotes
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof NotesGet200ResponseOneOfNotes
     */
    lastModified?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof NotesGet200ResponseOneOfNotes
     */
    userId?: string;
    /**
     * 
     * @type {NotesGet200ResponseOneOfNotesVerses}
     * @memberof NotesGet200ResponseOneOfNotes
     */
    verses?: NotesGet200ResponseOneOfNotesVerses;
}

/**
 * Check if a given object implements the NotesGet200ResponseOneOfNotes interface.
 */
export function instanceOfNotesGet200ResponseOneOfNotes(value: object): value is NotesGet200ResponseOneOfNotes {
    return true;
}

export function NotesGet200ResponseOneOfNotesFromJSON(json: any): NotesGet200ResponseOneOfNotes {
    return NotesGet200ResponseOneOfNotesFromJSONTyped(json, false);
}

export function NotesGet200ResponseOneOfNotesFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotesGet200ResponseOneOfNotes {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'verseId': json['verse_id'] == null ? undefined : json['verse_id'],
        'content': json['content'] == null ? undefined : json['content'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'lastModified': json['last_modified'] == null ? undefined : (new Date(json['last_modified'])),
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'verses': json['verses'] == null ? undefined : NotesGet200ResponseOneOfNotesVersesFromJSON(json['verses']),
    };
}

export function NotesGet200ResponseOneOfNotesToJSON(json: any): NotesGet200ResponseOneOfNotes {
    return NotesGet200ResponseOneOfNotesToJSONTyped(json, false);
}

export function NotesGet200ResponseOneOfNotesToJSONTyped(value?: NotesGet200ResponseOneOfNotes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'verse_id': value['verseId'],
        'content': value['content'],
        'created_at': value['createdAt'] === null ? null : ((value['createdAt'] as any)?.toISOString()),
        'last_modified': value['lastModified'] === null ? null : ((value['lastModified'] as any)?.toISOString()),
        'user_id': value['userId'],
        'verses': NotesGet200ResponseOneOfNotesVersesToJSON(value['verses']),
    };
}

