/* tslint:disable */
/* eslint-disable */
/**
 * Hey Bible App API
 * Public API for accessing Bible app data
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotesGet200ResponseOneOfNote } from './NotesGet200ResponseOneOfNote';
import {
    NotesGet200ResponseOneOfNoteFromJSON,
    NotesGet200ResponseOneOfNoteFromJSONTyped,
    NotesGet200ResponseOneOfNoteToJSON,
    NotesGet200ResponseOneOfNoteToJSONTyped,
} from './NotesGet200ResponseOneOfNote';

/**
 * Single note response (when ID is specified)
 * @export
 * @interface NotesGet200ResponseOneOf
 */
export interface NotesGet200ResponseOneOf {
    /**
     * 
     * @type {NotesGet200ResponseOneOfNote}
     * @memberof NotesGet200ResponseOneOf
     */
    note?: NotesGet200ResponseOneOfNote;
}

/**
 * Check if a given object implements the NotesGet200ResponseOneOf interface.
 */
export function instanceOfNotesGet200ResponseOneOf(value: object): value is NotesGet200ResponseOneOf {
    return true;
}

export function NotesGet200ResponseOneOfFromJSON(json: any): NotesGet200ResponseOneOf {
    return NotesGet200ResponseOneOfFromJSONTyped(json, false);
}

export function NotesGet200ResponseOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotesGet200ResponseOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'note': json['note'] == null ? undefined : NotesGet200ResponseOneOfNoteFromJSON(json['note']),
    };
}

export function NotesGet200ResponseOneOfToJSON(json: any): NotesGet200ResponseOneOf {
    return NotesGet200ResponseOneOfToJSONTyped(json, false);
}

export function NotesGet200ResponseOneOfToJSONTyped(value?: NotesGet200ResponseOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'note': NotesGet200ResponseOneOfNoteToJSON(value['note']),
    };
}

