/* tslint:disable */
/* eslint-disable */
/**
 * Hey Bible App API
 * Public API for accessing Bible app data
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotesGet200ResponseOneOfNotes } from './NotesGet200ResponseOneOfNotes';
import {
    NotesGet200ResponseOneOfNotesFromJSON,
    NotesGet200ResponseOneOfNotesFromJSONTyped,
    NotesGet200ResponseOneOfNotesToJSON,
    NotesGet200ResponseOneOfNotesToJSONTyped,
} from './NotesGet200ResponseOneOfNotes';

/**
 * Single note response (when ID is specified)
 * @export
 * @interface NotesGet200ResponseOneOf
 */
export interface NotesGet200ResponseOneOf {
    /**
     * 
     * @type {NotesGet200ResponseOneOfNotes}
     * @memberof NotesGet200ResponseOneOf
     */
    notes?: NotesGet200ResponseOneOfNotes;
}

/**
 * Check if a given object implements the NotesGet200ResponseOneOf interface.
 */
export function instanceOfNotesGet200ResponseOneOf(value: object): value is NotesGet200ResponseOneOf {
    return true;
}

export function NotesGet200ResponseOneOfFromJSON(json: any): NotesGet200ResponseOneOf {
    return NotesGet200ResponseOneOfFromJSONTyped(json, false);
}

export function NotesGet200ResponseOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotesGet200ResponseOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'notes': json['notes'] == null ? undefined : NotesGet200ResponseOneOfNotesFromJSON(json['notes']),
    };
}

export function NotesGet200ResponseOneOfToJSON(json: any): NotesGet200ResponseOneOf {
    return NotesGet200ResponseOneOfToJSONTyped(json, false);
}

export function NotesGet200ResponseOneOfToJSONTyped(value?: NotesGet200ResponseOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'notes': NotesGet200ResponseOneOfNotesToJSON(value['notes']),
    };
}

