/* tslint:disable */
/* eslint-disable */
/**
 * Hey Bible App API
 * Public API for accessing Bible app data
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotesGet200ResponseOneOfNoteVerses } from './NotesGet200ResponseOneOfNoteVerses';
import {
    NotesGet200ResponseOneOfNoteVersesFromJSON,
    NotesGet200ResponseOneOfNoteVersesFromJSONTyped,
    NotesGet200ResponseOneOfNoteVersesToJSON,
    NotesGet200ResponseOneOfNoteVersesToJSONTyped,
} from './NotesGet200ResponseOneOfNoteVerses';

/**
 * 
 * @export
 * @interface NotesGet200ResponseOneOfNote
 */
export interface NotesGet200ResponseOneOfNote {
    /**
     * 
     * @type {number}
     * @memberof NotesGet200ResponseOneOfNote
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof NotesGet200ResponseOneOfNote
     */
    verseId?: number;
    /**
     * 
     * @type {string}
     * @memberof NotesGet200ResponseOneOfNote
     */
    content?: string;
    /**
     * 
     * @type {Date}
     * @memberof NotesGet200ResponseOneOfNote
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof NotesGet200ResponseOneOfNote
     */
    lastModified?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof NotesGet200ResponseOneOfNote
     */
    userId?: string;
    /**
     * 
     * @type {NotesGet200ResponseOneOfNoteVerses}
     * @memberof NotesGet200ResponseOneOfNote
     */
    verses?: NotesGet200ResponseOneOfNoteVerses;
}

/**
 * Check if a given object implements the NotesGet200ResponseOneOfNote interface.
 */
export function instanceOfNotesGet200ResponseOneOfNote(value: object): value is NotesGet200ResponseOneOfNote {
    return true;
}

export function NotesGet200ResponseOneOfNoteFromJSON(json: any): NotesGet200ResponseOneOfNote {
    return NotesGet200ResponseOneOfNoteFromJSONTyped(json, false);
}

export function NotesGet200ResponseOneOfNoteFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotesGet200ResponseOneOfNote {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'verseId': json['verse_id'] == null ? undefined : json['verse_id'],
        'content': json['content'] == null ? undefined : json['content'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'lastModified': json['last_modified'] == null ? undefined : (new Date(json['last_modified'])),
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'verses': json['verses'] == null ? undefined : NotesGet200ResponseOneOfNoteVersesFromJSON(json['verses']),
    };
}

export function NotesGet200ResponseOneOfNoteToJSON(json: any): NotesGet200ResponseOneOfNote {
    return NotesGet200ResponseOneOfNoteToJSONTyped(json, false);
}

export function NotesGet200ResponseOneOfNoteToJSONTyped(value?: NotesGet200ResponseOneOfNote | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'verse_id': value['verseId'],
        'content': value['content'],
        'created_at': value['createdAt'] === null ? null : ((value['createdAt'] as any)?.toISOString()),
        'last_modified': value['lastModified'] === null ? null : ((value['lastModified'] as any)?.toISOString()),
        'user_id': value['userId'],
        'verses': NotesGet200ResponseOneOfNoteVersesToJSON(value['verses']),
    };
}

