/* tslint:disable */
/* eslint-disable */
/**
 * Hey Bible App API
 * Public API for accessing Bible app data
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotesGet200ResponseNotesInner } from './NotesGet200ResponseNotesInner';
import {
    NotesGet200ResponseNotesInnerFromJSON,
    NotesGet200ResponseNotesInnerFromJSONTyped,
    NotesGet200ResponseNotesInnerToJSON,
    NotesGet200ResponseNotesInnerToJSONTyped,
} from './NotesGet200ResponseNotesInner';

/**
 * 
 * @export
 * @interface NotesGet200Response
 */
export interface NotesGet200Response {
    /**
     * 
     * @type {Array<NotesGet200ResponseNotesInner>}
     * @memberof NotesGet200Response
     */
    notes?: Array<NotesGet200ResponseNotesInner>;
}

/**
 * Check if a given object implements the NotesGet200Response interface.
 */
export function instanceOfNotesGet200Response(value: object): value is NotesGet200Response {
    return true;
}

export function NotesGet200ResponseFromJSON(json: any): NotesGet200Response {
    return NotesGet200ResponseFromJSONTyped(json, false);
}

export function NotesGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotesGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'notes': json['notes'] == null ? undefined : ((json['notes'] as Array<any>).map(NotesGet200ResponseNotesInnerFromJSON)),
    };
}

export function NotesGet200ResponseToJSON(json: any): NotesGet200Response {
    return NotesGet200ResponseToJSONTyped(json, false);
}

export function NotesGet200ResponseToJSONTyped(value?: NotesGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'notes': value['notes'] == null ? undefined : ((value['notes'] as Array<any>).map(NotesGet200ResponseNotesInnerToJSON)),
    };
}

