/* tslint:disable */
/* eslint-disable */
/**
 * Hey Bible App API
 * Public API for accessing Bible app data
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SearchGet200ResponseVerse } from './SearchGet200ResponseVerse';
import {
    SearchGet200ResponseVerseFromJSON,
    SearchGet200ResponseVerseFromJSONTyped,
    SearchGet200ResponseVerseToJSON,
    SearchGet200ResponseVerseToJSONTyped,
} from './SearchGet200ResponseVerse';

/**
 * 
 * @export
 * @interface SearchGet200Response
 */
export interface SearchGet200Response {
    /**
     * 
     * @type {SearchGet200ResponseVerse}
     * @memberof SearchGet200Response
     */
    verse?: SearchGet200ResponseVerse;
}

/**
 * Check if a given object implements the SearchGet200Response interface.
 */
export function instanceOfSearchGet200Response(value: object): value is SearchGet200Response {
    return true;
}

export function SearchGet200ResponseFromJSON(json: any): SearchGet200Response {
    return SearchGet200ResponseFromJSONTyped(json, false);
}

export function SearchGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'verse': json['verse'] == null ? undefined : SearchGet200ResponseVerseFromJSON(json['verse']),
    };
}

export function SearchGet200ResponseToJSON(json: any): SearchGet200Response {
    return SearchGet200ResponseToJSONTyped(json, false);
}

export function SearchGet200ResponseToJSONTyped(value?: SearchGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'verse': SearchGet200ResponseVerseToJSON(value['verse']),
    };
}

