/* tslint:disable */
/* eslint-disable */
/**
 * Hey Bible App API
 * Public API for accessing Bible app data
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchGet200ResponseVerse
 */
export interface SearchGet200ResponseVerse {
    /**
     * 
     * @type {number}
     * @memberof SearchGet200ResponseVerse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof SearchGet200ResponseVerse
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchGet200ResponseVerse
     */
    bibleId?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchGet200ResponseVerse
     */
    book?: string;
    /**
     * 
     * @type {number}
     * @memberof SearchGet200ResponseVerse
     */
    chapter?: number;
    /**
     * 
     * @type {number}
     * @memberof SearchGet200ResponseVerse
     */
    startVerse?: number;
    /**
     * 
     * @type {number}
     * @memberof SearchGet200ResponseVerse
     */
    endVerse?: number;
    /**
     * HTML content with superscript verse numbers
     * @type {string}
     * @memberof SearchGet200ResponseVerse
     */
    content?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SearchGet200ResponseVerse
     */
    isFavorite?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof SearchGet200ResponseVerse
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof SearchGet200ResponseVerse
     */
    lastUpdated?: Date;
}

/**
 * Check if a given object implements the SearchGet200ResponseVerse interface.
 */
export function instanceOfSearchGet200ResponseVerse(value: object): value is SearchGet200ResponseVerse {
    return true;
}

export function SearchGet200ResponseVerseFromJSON(json: any): SearchGet200ResponseVerse {
    return SearchGet200ResponseVerseFromJSONTyped(json, false);
}

export function SearchGet200ResponseVerseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchGet200ResponseVerse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'bibleId': json['bible_id'] == null ? undefined : json['bible_id'],
        'book': json['book'] == null ? undefined : json['book'],
        'chapter': json['chapter'] == null ? undefined : json['chapter'],
        'startVerse': json['start_verse'] == null ? undefined : json['start_verse'],
        'endVerse': json['end_verse'] == null ? undefined : json['end_verse'],
        'content': json['content'] == null ? undefined : json['content'],
        'isFavorite': json['is_favorite'] == null ? undefined : json['is_favorite'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'lastUpdated': json['last_updated'] == null ? undefined : (new Date(json['last_updated'])),
    };
}

export function SearchGet200ResponseVerseToJSON(json: any): SearchGet200ResponseVerse {
    return SearchGet200ResponseVerseToJSONTyped(json, false);
}

export function SearchGet200ResponseVerseToJSONTyped(value?: SearchGet200ResponseVerse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'user_id': value['userId'],
        'bible_id': value['bibleId'],
        'book': value['book'],
        'chapter': value['chapter'],
        'start_verse': value['startVerse'],
        'end_verse': value['endVerse'],
        'content': value['content'],
        'is_favorite': value['isFavorite'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'last_updated': value['lastUpdated'] == null ? undefined : ((value['lastUpdated']).toISOString()),
    };
}

