/* tslint:disable */
/* eslint-disable */
/**
 * Hey Bible App API
 * Public API for accessing Bible app data
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TagsGet200ResponseTagsInner } from './TagsGet200ResponseTagsInner';
import {
    TagsGet200ResponseTagsInnerFromJSON,
    TagsGet200ResponseTagsInnerFromJSONTyped,
    TagsGet200ResponseTagsInnerToJSON,
    TagsGet200ResponseTagsInnerToJSONTyped,
} from './TagsGet200ResponseTagsInner';

/**
 * 
 * @export
 * @interface TagsGet200Response
 */
export interface TagsGet200Response {
    /**
     * 
     * @type {Array<TagsGet200ResponseTagsInner>}
     * @memberof TagsGet200Response
     */
    tags?: Array<TagsGet200ResponseTagsInner>;
}

/**
 * Check if a given object implements the TagsGet200Response interface.
 */
export function instanceOfTagsGet200Response(value: object): value is TagsGet200Response {
    return true;
}

export function TagsGet200ResponseFromJSON(json: any): TagsGet200Response {
    return TagsGet200ResponseFromJSONTyped(json, false);
}

export function TagsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'tags': json['tags'] == null ? undefined : ((json['tags'] as Array<any>).map(TagsGet200ResponseTagsInnerFromJSON)),
    };
}

export function TagsGet200ResponseToJSON(json: any): TagsGet200Response {
    return TagsGet200ResponseToJSONTyped(json, false);
}

export function TagsGet200ResponseToJSONTyped(value?: TagsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tags': value['tags'] == null ? undefined : ((value['tags'] as Array<any>).map(TagsGet200ResponseTagsInnerToJSON)),
    };
}

