/* tslint:disable */
/* eslint-disable */
/**
 * Hey Bible App API
 * Public API for accessing Bible app data
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { VersesGet200ResponseOneOf } from './VersesGet200ResponseOneOf';
import {
    instanceOfVersesGet200ResponseOneOf,
    VersesGet200ResponseOneOfFromJSON,
    VersesGet200ResponseOneOfFromJSONTyped,
    VersesGet200ResponseOneOfToJSON,
} from './VersesGet200ResponseOneOf';
import type { VersesGet200ResponseOneOf1 } from './VersesGet200ResponseOneOf1';
import {
    instanceOfVersesGet200ResponseOneOf1,
    VersesGet200ResponseOneOf1FromJSON,
    VersesGet200ResponseOneOf1FromJSONTyped,
    VersesGet200ResponseOneOf1ToJSON,
} from './VersesGet200ResponseOneOf1';

/**
 * @type VersesGet200Response
 * 
 * @export
 */
export type VersesGet200Response = VersesGet200ResponseOneOf | VersesGet200ResponseOneOf1;

export function VersesGet200ResponseFromJSON(json: any): VersesGet200Response {
    return VersesGet200ResponseFromJSONTyped(json, false);
}

export function VersesGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersesGet200Response {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfVersesGet200ResponseOneOf(json)) {
        return VersesGet200ResponseOneOfFromJSONTyped(json, true);
    }
    if (instanceOfVersesGet200ResponseOneOf1(json)) {
        return VersesGet200ResponseOneOf1FromJSONTyped(json, true);
    }

    return {} as any;
}

export function VersesGet200ResponseToJSON(json: any): any {
    return VersesGet200ResponseToJSONTyped(json, false);
}

export function VersesGet200ResponseToJSONTyped(value?: VersesGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfVersesGet200ResponseOneOf(value)) {
        return VersesGet200ResponseOneOfToJSON(value as VersesGet200ResponseOneOf);
    }
    if (instanceOfVersesGet200ResponseOneOf1(value)) {
        return VersesGet200ResponseOneOf1ToJSON(value as VersesGet200ResponseOneOf1);
    }

    return {};
}

