/* tslint:disable */
/* eslint-disable */
/**
 * Hey Bible App API
 * Public API for accessing Bible app data
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VersesGet200ResponseVersesInner } from './VersesGet200ResponseVersesInner';
import {
    VersesGet200ResponseVersesInnerFromJSON,
    VersesGet200ResponseVersesInnerFromJSONTyped,
    VersesGet200ResponseVersesInnerToJSON,
    VersesGet200ResponseVersesInnerToJSONTyped,
} from './VersesGet200ResponseVersesInner';

/**
 * 
 * @export
 * @interface VersesGet200Response
 */
export interface VersesGet200Response {
    /**
     * 
     * @type {Array<VersesGet200ResponseVersesInner>}
     * @memberof VersesGet200Response
     */
    verses?: Array<VersesGet200ResponseVersesInner>;
}

/**
 * Check if a given object implements the VersesGet200Response interface.
 */
export function instanceOfVersesGet200Response(value: object): value is VersesGet200Response {
    return true;
}

export function VersesGet200ResponseFromJSON(json: any): VersesGet200Response {
    return VersesGet200ResponseFromJSONTyped(json, false);
}

export function VersesGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersesGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'verses': json['verses'] == null ? undefined : ((json['verses'] as Array<any>).map(VersesGet200ResponseVersesInnerFromJSON)),
    };
}

export function VersesGet200ResponseToJSON(json: any): VersesGet200Response {
    return VersesGet200ResponseToJSONTyped(json, false);
}

export function VersesGet200ResponseToJSONTyped(value?: VersesGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'verses': value['verses'] == null ? undefined : ((value['verses'] as Array<any>).map(VersesGet200ResponseVersesInnerToJSON)),
    };
}

