/* tslint:disable */
/* eslint-disable */
/**
 * Hey Bible App API
 * Public API for accessing Bible app data
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BiblesGet200Response,
  BooksGet200Response,
  ChatsGet200Response,
  FavoritesGet200Response,
  ImagesGet200Response,
  NotesGet200Response,
  SearchGet200Response,
  TagsGet200Response,
} from '../models/index';
import {
    BiblesGet200ResponseFromJSON,
    BiblesGet200ResponseToJSON,
    BooksGet200ResponseFromJSON,
    BooksGet200ResponseToJSON,
    ChatsGet200ResponseFromJSON,
    ChatsGet200ResponseToJSON,
    FavoritesGet200ResponseFromJSON,
    FavoritesGet200ResponseToJSON,
    ImagesGet200ResponseFromJSON,
    ImagesGet200ResponseToJSON,
    NotesGet200ResponseFromJSON,
    NotesGet200ResponseToJSON,
    SearchGet200ResponseFromJSON,
    SearchGet200ResponseToJSON,
    TagsGet200ResponseFromJSON,
    TagsGet200ResponseToJSON,
} from '../models/index';

export interface ChatsGetRequest {
    id?: string;
    limit?: number;
    offset?: number;
}

export interface FavoritesGetRequest {
    tag?: string;
    limit?: number;
    offset?: number;
}

export interface ImagesGetRequest {
    id?: number;
    limit?: number;
    offset?: number;
}

export interface NotesGetRequest {
    id?: number;
    limit?: number;
    offset?: number;
}

export interface SearchGetRequest {
    book: string;
    chapter: number;
    startVerse?: number;
    endVerse?: number;
    bibleId?: string;
}

/**
 * HeyBibleApi - interface
 * 
 * @export
 * @interface HeyBibleApiInterface
 */
export interface HeyBibleApiInterface {
    /**
     * Retrieve Bible translations available to the user
     * @summary Get available Bibles
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HeyBibleApiInterface
     */
    biblesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BiblesGet200Response>>;

    /**
     * Retrieve Bible translations available to the user
     * Get available Bibles
     */
    biblesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BiblesGet200Response>;

    /**
     * Retrieve the list of Bible books with their codes and chapter counts
     * @summary Get Bible books
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HeyBibleApiInterface
     */
    booksGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BooksGet200Response>>;

    /**
     * Retrieve the list of Bible books with their codes and chapter counts
     * Get Bible books
     */
    booksGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BooksGet200Response>;

    /**
     * Retrieve the user\'s chat conversations with verse context. If ID is provided, returns a single chat with its messages.
     * @summary Get chats
     * @param {string} [id] Specific chat ID to retrieve (returns full chat with messages)
     * @param {number} [limit] Number of chats to return (ignored if ID is specified)
     * @param {number} [offset] Number of chats to skip (ignored if ID is specified)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HeyBibleApiInterface
     */
    chatsGetRaw(requestParameters: ChatsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChatsGet200Response>>;

    /**
     * Retrieve the user\'s chat conversations with verse context. If ID is provided, returns a single chat with its messages.
     * Get chats
     */
    chatsGet(requestParameters: ChatsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChatsGet200Response>;

    /**
     * Retrieve the user\'s favorited verses with notes, images, conversations, and tags. Optionally filter by tag name.
     * @summary Get favorite verses
     * @param {string} [tag] Filter favorites by tag name
     * @param {number} [limit] Number of favorites to return
     * @param {number} [offset] Number of favorites to skip
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HeyBibleApiInterface
     */
    favoritesGetRaw(requestParameters: FavoritesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FavoritesGet200Response>>;

    /**
     * Retrieve the user\'s favorited verses with notes, images, conversations, and tags. Optionally filter by tag name.
     * Get favorite verses
     */
    favoritesGet(requestParameters: FavoritesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FavoritesGet200Response>;

    /**
     * Retrieve a list of images with their associated verses, or a specific image if ID is provided
     * @summary Get user\'s images
     * @param {number} [id] Specific image ID to retrieve (returns signed URL)
     * @param {number} [limit] Number of images to return (ignored if ID is specified)
     * @param {number} [offset] Number of images to skip (ignored if ID is specified)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HeyBibleApiInterface
     */
    imagesGetRaw(requestParameters: ImagesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ImagesGet200Response>>;

    /**
     * Retrieve a list of images with their associated verses, or a specific image if ID is provided
     * Get user\'s images
     */
    imagesGet(requestParameters: ImagesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ImagesGet200Response>;

    /**
     * Retrieve all notes with their associated verses for the user, or a specific note if ID is provided
     * @summary Get notes
     * @param {number} [id] Specific note ID to retrieve
     * @param {number} [limit] Number of notes to return (ignored if ID is specified)
     * @param {number} [offset] Number of notes to skip (ignored if ID is specified)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HeyBibleApiInterface
     */
    notesGetRaw(requestParameters: NotesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NotesGet200Response>>;

    /**
     * Retrieve all notes with their associated verses for the user, or a specific note if ID is provided
     * Get notes
     */
    notesGet(requestParameters: NotesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NotesGet200Response>;

    /**
     * Search for Bible verses by book and chapter. Saves the result to the user\'s account. If start_verse and end_verse are omitted, returns the full chapter.
     * @summary Search for verses
     * @param {string} book Book name (e.g. \&quot;John\&quot;, \&quot;Genesis\&quot;, \&quot;1 Corinthians\&quot;)
     * @param {number} chapter Chapter number
     * @param {number} [startVerse] Starting verse number (defaults to 1)
     * @param {number} [endVerse] Ending verse number (defaults to last verse in chapter)
     * @param {string} [bibleId] Bible translation ID (defaults to ESV). Use /bibles to get available IDs.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HeyBibleApiInterface
     */
    searchGetRaw(requestParameters: SearchGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchGet200Response>>;

    /**
     * Search for Bible verses by book and chapter. Saves the result to the user\'s account. If start_verse and end_verse are omitted, returns the full chapter.
     * Search for verses
     */
    searchGet(requestParameters: SearchGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchGet200Response>;

    /**
     * Retrieve all tags defined by the user
     * @summary Get tags
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HeyBibleApiInterface
     */
    tagsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TagsGet200Response>>;

    /**
     * Retrieve all tags defined by the user
     * Get tags
     */
    tagsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TagsGet200Response>;

}

/**
 * 
 */
export class HeyBibleApi extends runtime.BaseAPI implements HeyBibleApiInterface {

    /**
     * Retrieve Bible translations available to the user
     * Get available Bibles
     */
    async biblesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BiblesGet200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Hey-Bible-Api-Key"] = await this.configuration.apiKey("X-Hey-Bible-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/bibles`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BiblesGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve Bible translations available to the user
     * Get available Bibles
     */
    async biblesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BiblesGet200Response> {
        const response = await this.biblesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Retrieve the list of Bible books with their codes and chapter counts
     * Get Bible books
     */
    async booksGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BooksGet200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Hey-Bible-Api-Key"] = await this.configuration.apiKey("X-Hey-Bible-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/books`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BooksGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve the list of Bible books with their codes and chapter counts
     * Get Bible books
     */
    async booksGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BooksGet200Response> {
        const response = await this.booksGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Retrieve the user\'s chat conversations with verse context. If ID is provided, returns a single chat with its messages.
     * Get chats
     */
    async chatsGetRaw(requestParameters: ChatsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChatsGet200Response>> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Hey-Bible-Api-Key"] = await this.configuration.apiKey("X-Hey-Bible-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/chats`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChatsGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve the user\'s chat conversations with verse context. If ID is provided, returns a single chat with its messages.
     * Get chats
     */
    async chatsGet(requestParameters: ChatsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChatsGet200Response> {
        const response = await this.chatsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve the user\'s favorited verses with notes, images, conversations, and tags. Optionally filter by tag name.
     * Get favorite verses
     */
    async favoritesGetRaw(requestParameters: FavoritesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FavoritesGet200Response>> {
        const queryParameters: any = {};

        if (requestParameters['tag'] != null) {
            queryParameters['tag'] = requestParameters['tag'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Hey-Bible-Api-Key"] = await this.configuration.apiKey("X-Hey-Bible-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/favorites`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FavoritesGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve the user\'s favorited verses with notes, images, conversations, and tags. Optionally filter by tag name.
     * Get favorite verses
     */
    async favoritesGet(requestParameters: FavoritesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FavoritesGet200Response> {
        const response = await this.favoritesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve a list of images with their associated verses, or a specific image if ID is provided
     * Get user\'s images
     */
    async imagesGetRaw(requestParameters: ImagesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ImagesGet200Response>> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Hey-Bible-Api-Key"] = await this.configuration.apiKey("X-Hey-Bible-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/images`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ImagesGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve a list of images with their associated verses, or a specific image if ID is provided
     * Get user\'s images
     */
    async imagesGet(requestParameters: ImagesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ImagesGet200Response> {
        const response = await this.imagesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve all notes with their associated verses for the user, or a specific note if ID is provided
     * Get notes
     */
    async notesGetRaw(requestParameters: NotesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NotesGet200Response>> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Hey-Bible-Api-Key"] = await this.configuration.apiKey("X-Hey-Bible-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/notes`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NotesGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve all notes with their associated verses for the user, or a specific note if ID is provided
     * Get notes
     */
    async notesGet(requestParameters: NotesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NotesGet200Response> {
        const response = await this.notesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Search for Bible verses by book and chapter. Saves the result to the user\'s account. If start_verse and end_verse are omitted, returns the full chapter.
     * Search for verses
     */
    async searchGetRaw(requestParameters: SearchGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchGet200Response>> {
        if (requestParameters['book'] == null) {
            throw new runtime.RequiredError(
                'book',
                'Required parameter "book" was null or undefined when calling searchGet().'
            );
        }

        if (requestParameters['chapter'] == null) {
            throw new runtime.RequiredError(
                'chapter',
                'Required parameter "chapter" was null or undefined when calling searchGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['book'] != null) {
            queryParameters['book'] = requestParameters['book'];
        }

        if (requestParameters['chapter'] != null) {
            queryParameters['chapter'] = requestParameters['chapter'];
        }

        if (requestParameters['startVerse'] != null) {
            queryParameters['start_verse'] = requestParameters['startVerse'];
        }

        if (requestParameters['endVerse'] != null) {
            queryParameters['end_verse'] = requestParameters['endVerse'];
        }

        if (requestParameters['bibleId'] != null) {
            queryParameters['bible_id'] = requestParameters['bibleId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Hey-Bible-Api-Key"] = await this.configuration.apiKey("X-Hey-Bible-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/search`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SearchGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Search for Bible verses by book and chapter. Saves the result to the user\'s account. If start_verse and end_verse are omitted, returns the full chapter.
     * Search for verses
     */
    async searchGet(requestParameters: SearchGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchGet200Response> {
        const response = await this.searchGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve all tags defined by the user
     * Get tags
     */
    async tagsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TagsGet200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Hey-Bible-Api-Key"] = await this.configuration.apiKey("X-Hey-Bible-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/tags`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TagsGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve all tags defined by the user
     * Get tags
     */
    async tagsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TagsGet200Response> {
        const response = await this.tagsGetRaw(initOverrides);
        return await response.value();
    }

}
